// Generated by supabase_typegen 0.4.0 from GeneratorMetadata version 1.
// Do not edit by hand.
//
// Source schemas: graphql_public, public

// The typed table access API is still experimental.
// ignore_for_file: experimental_member_use

import 'package:supabase_flutter/supabase_flutter.dart';

/// A row of the `consent_events` table.
/// Append-only history of consent per user, purpose and notice version: journal
/// (Art. 9 (2) (a) GDPR) and usage_analytics (§ 25 TDDDG).
extension type const ConsentEventsRow(Map<String, dynamic> _json)
    implements Object {
  /// granted, or withdrawn (Art. 7 (3)). The latest one is the current state.
  String get action => _json['action'] as String;

  /// What the consent is to; each purpose has its own versions and history.
  String get purpose => _json['purpose'] as String;
  DateTime get recordedAt => DateTime.parse(_json['recorded_at'] as String);
  int get seq => _json['seq'] as int;
  String get userId => _json['user_id'] as String;

  /// Names the notice wording; the text lives on the site, never per user.
  String get version => _json['version'] as String;

  /// The row as decoded from the response.
  Map<String, dynamic> toJson() => _json;
}

/// Values for inserting a row into `consent_events`. Columns that are nullable,
/// identity, or covered by a database default are optional; passing `null`
/// omits the column so the database default applies. Columns the database
/// always generates itself are left out entirely. Use the `set…ToNull` methods
/// to insert SQL NULL explicitly.
extension type const ConsentEventsInsert._(Map<String, dynamic> _json)
    implements Object {
  ConsentEventsInsert({
    required String action,
    required String purpose,
    DateTime? recordedAt,
    required String userId,
    required String version,
  }) : this._({
         'action': action,
         'purpose': purpose,
         'recorded_at': ?recordedAt?.toUtc().toIso8601String(),
         'user_id': userId,
         'version': version,
       });
}

/// Values for updating rows of `consent_events`. All columns are optional;
/// passing `null` omits the column, leaving it unchanged. Use the `set…ToNull`
/// methods to write SQL NULL explicitly.
extension type const ConsentEventsUpdate._(Map<String, dynamic> _json)
    implements Object {
  ConsentEventsUpdate({
    String? action,
    String? purpose,
    DateTime? recordedAt,
    String? userId,
    String? version,
  }) : this._({
         'action': ?action,
         'purpose': ?purpose,
         'recorded_at': ?recordedAt?.toUtc().toIso8601String(),
         'user_id': ?userId,
         'version': ?version,
       });
}

/// Typed access to the `consent_events` table.
class ConsentEvents {
  const ConsentEvents._();

  /// Table definition for [PostgrestClient.table].
  static const table =
      PostgrestTable<
        ConsentEventsRow,
        ConsentEventsInsert,
        ConsentEventsUpdate
      >(
        'consent_events',
        ConsentEventsRow.new,
        schema: 'public',
        primaryKey: [seq],
      );

  static const action = PostgrestColumn<ConsentEventsRow, String>('action');
  static const purpose = PostgrestColumn<ConsentEventsRow, String>('purpose');
  static const recordedAt = PostgrestColumn<ConsentEventsRow, DateTime>(
    'recorded_at',
  );
  static const seq = PostgrestColumn<ConsentEventsRow, int>('seq');
  static const userId = PostgrestColumn<ConsentEventsRow, String>('user_id');
  static const version = PostgrestColumn<ConsentEventsRow, String>('version');
}

/// A row of the `entries` table.
/// A finished journal entry. Written once; deleted with the account.
extension type const EntriesRow(Map<String, dynamic> _json) implements Object {
  Object? get answers => _json['answers'] as Object?;
  DateTime get createdAt => DateTime.parse(_json['created_at'] as String);
  String get id => _json['id'] as String;
  Object? get questions => _json['questions'] as Object?;
  String? get sessionId => _json['session_id'] as String?;
  String get summary => _json['summary'] as String;
  String get userId => _json['user_id'] as String;

  /// The row as decoded from the response.
  Map<String, dynamic> toJson() => _json;
}

/// Values for inserting a row into `entries`. Columns that are nullable,
/// identity, or covered by a database default are optional; passing `null`
/// omits the column so the database default applies. Columns the database
/// always generates itself are left out entirely. Use the `set…ToNull` methods
/// to insert SQL NULL explicitly.
extension type const EntriesInsert._(Map<String, dynamic> _json)
    implements Object {
  EntriesInsert({
    required Object answers,
    DateTime? createdAt,
    String? id,
    required Object questions,
    String? sessionId,
    required String summary,
    String? userId,
  }) : this._({
         'answers': answers,
         'created_at': ?createdAt?.toUtc().toIso8601String(),
         'id': ?id,
         'questions': questions,
         'session_id': ?sessionId,
         'summary': summary,
         'user_id': ?userId,
       });

  /// Returns a copy with `session_id` set to SQL NULL, overriding any database
  /// default.
  EntriesInsert setSessionIdToNull() =>
      EntriesInsert._({..._json, 'session_id': null});
}

/// Values for updating rows of `entries`. All columns are optional; passing
/// `null` omits the column, leaving it unchanged. Use the `set…ToNull` methods
/// to write SQL NULL explicitly.
extension type const EntriesUpdate._(Map<String, dynamic> _json)
    implements Object {
  EntriesUpdate({
    Object? answers,
    DateTime? createdAt,
    String? id,
    Object? questions,
    String? sessionId,
    String? summary,
    String? userId,
  }) : this._({
         'answers': ?answers,
         'created_at': ?createdAt?.toUtc().toIso8601String(),
         'id': ?id,
         'questions': ?questions,
         'session_id': ?sessionId,
         'summary': ?summary,
         'user_id': ?userId,
       });

  /// Returns a copy with `session_id` set to SQL NULL, overriding any database
  /// default.
  EntriesUpdate setSessionIdToNull() =>
      EntriesUpdate._({..._json, 'session_id': null});
}

/// Typed access to the `entries` table.
class Entries {
  const Entries._();

  /// Table definition for [PostgrestClient.table].
  static const table = PostgrestTable<EntriesRow, EntriesInsert, EntriesUpdate>(
    'entries',
    EntriesRow.new,
    schema: 'public',
    primaryKey: [id],
    relations: [sessions],
  );

  static const answers = PostgrestColumn<EntriesRow, Object>('answers');
  static const createdAt = PostgrestColumn<EntriesRow, DateTime>('created_at');
  static const id = PostgrestColumn<EntriesRow, String>('id');
  static const questions = PostgrestColumn<EntriesRow, Object>('questions');
  static const sessionId = PostgrestNullableColumn<EntriesRow, String>(
    'session_id',
  );
  static const summary = PostgrestColumn<EntriesRow, String>('summary');
  static const userId = PostgrestColumn<EntriesRow, String>('user_id');

  /// The `sessions` row referenced by `session_id`.
  static const sessions = PostgrestToOneRelation<EntriesRow, SessionsRow>(
    'sessions',
    columns: [sessionId],
    referencedTable: 'sessions',
    referencedColumns: [Sessions.id],
  );
}

/// A row of the `profiles` table.
/// What the user asked to be called; one row per user, deleted with the
/// account.
extension type const ProfilesRow(Map<String, dynamic> _json) implements Object {
  DateTime get createdAt => DateTime.parse(_json['created_at'] as String);

  /// 1-40 Unicode code points, trimmed as Dart trims, no control characters.
  String get displayName => _json['display_name'] as String;

  /// True when the app chose the name on Skip rather than the user typing it.
  bool get nameIsPlaceholder => _json['name_is_placeholder'] as bool;
  DateTime get updatedAt => DateTime.parse(_json['updated_at'] as String);
  String get userId => _json['user_id'] as String;

  /// The row as decoded from the response.
  Map<String, dynamic> toJson() => _json;
}

/// Values for inserting a row into `profiles`. Columns that are nullable,
/// identity, or covered by a database default are optional; passing `null`
/// omits the column so the database default applies. Columns the database
/// always generates itself are left out entirely. Use the `set…ToNull` methods
/// to insert SQL NULL explicitly.
extension type const ProfilesInsert._(Map<String, dynamic> _json)
    implements Object {
  ProfilesInsert({
    DateTime? createdAt,
    required String displayName,
    bool? nameIsPlaceholder,
    DateTime? updatedAt,
    String? userId,
  }) : this._({
         'created_at': ?createdAt?.toUtc().toIso8601String(),
         'display_name': displayName,
         'name_is_placeholder': ?nameIsPlaceholder,
         'updated_at': ?updatedAt?.toUtc().toIso8601String(),
         'user_id': ?userId,
       });
}

/// Values for updating rows of `profiles`. All columns are optional; passing
/// `null` omits the column, leaving it unchanged. Use the `set…ToNull` methods
/// to write SQL NULL explicitly.
extension type const ProfilesUpdate._(Map<String, dynamic> _json)
    implements Object {
  ProfilesUpdate({
    DateTime? createdAt,
    String? displayName,
    bool? nameIsPlaceholder,
    DateTime? updatedAt,
    String? userId,
  }) : this._({
         'created_at': ?createdAt?.toUtc().toIso8601String(),
         'display_name': ?displayName,
         'name_is_placeholder': ?nameIsPlaceholder,
         'updated_at': ?updatedAt?.toUtc().toIso8601String(),
         'user_id': ?userId,
       });
}

/// Typed access to the `profiles` table.
class Profiles {
  const Profiles._();

  /// Table definition for [PostgrestClient.table].
  static const table =
      PostgrestTable<ProfilesRow, ProfilesInsert, ProfilesUpdate>(
        'profiles',
        ProfilesRow.new,
        schema: 'public',
        primaryKey: [userId],
      );

  static const createdAt = PostgrestColumn<ProfilesRow, DateTime>('created_at');
  static const displayName = PostgrestColumn<ProfilesRow, String>(
    'display_name',
  );
  static const nameIsPlaceholder = PostgrestColumn<ProfilesRow, bool>(
    'name_is_placeholder',
  );
  static const updatedAt = PostgrestColumn<ProfilesRow, DateTime>('updated_at');
  static const userId = PostgrestColumn<ProfilesRow, String>('user_id');
}

/// A row of the `sessions` table.
/// One journaling conversation; the transcript is server-signed (ADR 0008).
extension type const SessionsRow(Map<String, dynamic> _json) implements Object {
  String? get appVersion => _json['app_version'] as String?;
  DateTime get createdAt => DateTime.parse(_json['created_at'] as String);
  String get id => _json['id'] as String;
  Object? get pending => _json['pending'] as Object?;
  String get questionSetId => _json['question_set_id'] as String;
  Object? get questions => _json['questions'] as Object?;
  String get signature => _json['signature'] as String;
  String get status => _json['status'] as String;
  Object? get transcript => _json['transcript'] as Object?;
  DateTime get updatedAt => DateTime.parse(_json['updated_at'] as String);
  String get userId => _json['user_id'] as String;

  /// The row as decoded from the response.
  Map<String, dynamic> toJson() => _json;
}

/// Values for inserting a row into `sessions`. Columns that are nullable,
/// identity, or covered by a database default are optional; passing `null`
/// omits the column so the database default applies. Columns the database
/// always generates itself are left out entirely. Use the `set…ToNull` methods
/// to insert SQL NULL explicitly.
extension type const SessionsInsert._(Map<String, dynamic> _json)
    implements Object {
  SessionsInsert({
    String? appVersion,
    DateTime? createdAt,
    String? id,
    Object? pending,
    required String questionSetId,
    Object? questions,
    required String signature,
    String? status,
    required Object transcript,
    DateTime? updatedAt,
    String? userId,
  }) : this._({
         'app_version': ?appVersion,
         'created_at': ?createdAt?.toUtc().toIso8601String(),
         'id': ?id,
         'pending': ?pending,
         'question_set_id': questionSetId,
         'questions': ?questions,
         'signature': signature,
         'status': ?status,
         'transcript': transcript,
         'updated_at': ?updatedAt?.toUtc().toIso8601String(),
         'user_id': ?userId,
       });

  /// Returns a copy with `app_version` set to SQL NULL, overriding any database
  /// default.
  SessionsInsert setAppVersionToNull() =>
      SessionsInsert._({..._json, 'app_version': null});

  /// Returns a copy with `pending` set to SQL NULL, overriding any database
  /// default.
  SessionsInsert setPendingToNull() =>
      SessionsInsert._({..._json, 'pending': null});
}

/// Values for updating rows of `sessions`. All columns are optional; passing
/// `null` omits the column, leaving it unchanged. Use the `set…ToNull` methods
/// to write SQL NULL explicitly.
extension type const SessionsUpdate._(Map<String, dynamic> _json)
    implements Object {
  SessionsUpdate({
    String? appVersion,
    DateTime? createdAt,
    String? id,
    Object? pending,
    String? questionSetId,
    Object? questions,
    String? signature,
    String? status,
    Object? transcript,
    DateTime? updatedAt,
    String? userId,
  }) : this._({
         'app_version': ?appVersion,
         'created_at': ?createdAt?.toUtc().toIso8601String(),
         'id': ?id,
         'pending': ?pending,
         'question_set_id': ?questionSetId,
         'questions': ?questions,
         'signature': ?signature,
         'status': ?status,
         'transcript': ?transcript,
         'updated_at': ?updatedAt?.toUtc().toIso8601String(),
         'user_id': ?userId,
       });

  /// Returns a copy with `app_version` set to SQL NULL, overriding any database
  /// default.
  SessionsUpdate setAppVersionToNull() =>
      SessionsUpdate._({..._json, 'app_version': null});

  /// Returns a copy with `pending` set to SQL NULL, overriding any database
  /// default.
  SessionsUpdate setPendingToNull() =>
      SessionsUpdate._({..._json, 'pending': null});
}

/// Typed access to the `sessions` table.
class Sessions {
  const Sessions._();

  /// Table definition for [PostgrestClient.table].
  static const table =
      PostgrestTable<SessionsRow, SessionsInsert, SessionsUpdate>(
        'sessions',
        SessionsRow.new,
        schema: 'public',
        primaryKey: [id],
        relations: [entries],
      );

  static const appVersion = PostgrestNullableColumn<SessionsRow, String>(
    'app_version',
  );
  static const createdAt = PostgrestColumn<SessionsRow, DateTime>('created_at');
  static const id = PostgrestColumn<SessionsRow, String>('id');
  static const pending = PostgrestNullableColumn<SessionsRow, Object>(
    'pending',
  );
  static const questionSetId = PostgrestColumn<SessionsRow, String>(
    'question_set_id',
  );
  static const questions = PostgrestColumn<SessionsRow, Object>('questions');
  static const signature = PostgrestColumn<SessionsRow, String>('signature');
  static const status = PostgrestColumn<SessionsRow, String>('status');
  static const transcript = PostgrestColumn<SessionsRow, Object>('transcript');
  static const updatedAt = PostgrestColumn<SessionsRow, DateTime>('updated_at');
  static const userId = PostgrestColumn<SessionsRow, String>('user_id');

  /// The `entries` row referencing this row through `session_id`.
  static const entries = PostgrestToOneRelation<SessionsRow, EntriesRow>(
    'entries',
    columns: [id],
    referencedTable: 'entries',
    referencedColumns: [Entries.sessionId],
  );
}

/// A row of the `waitlist` table.
/// Early-access sign-ups from the web site; append-only for the world.
extension type const WaitlistRow(Map<String, dynamic> _json) implements Object {
  /// Proof of the mailbox: the link in the confirmation mail carries it. Never
  /// granted to anon.
  String get confirmToken => _json['confirm_token'] as String;
  DateTime? get confirmedAt => switch (_json['confirmed_at']) {
    null => null,
    final Object value => DateTime.parse(value as String),
  };
  DateTime get createdAt => DateTime.parse(_json['created_at'] as String);
  String get email => _json['email'] as String;
  String get id => _json['id'] as String;
  String? get ip => _json['ip'] as String?;
  String? get source => _json['source'] as String?;

  /// The row as decoded from the response.
  Map<String, dynamic> toJson() => _json;
}

/// Values for inserting a row into `waitlist`. Columns that are nullable,
/// identity, or covered by a database default are optional; passing `null`
/// omits the column so the database default applies. Columns the database
/// always generates itself are left out entirely. Use the `set…ToNull` methods
/// to insert SQL NULL explicitly.
extension type const WaitlistInsert._(Map<String, dynamic> _json)
    implements Object {
  WaitlistInsert({
    String? confirmToken,
    DateTime? confirmedAt,
    DateTime? createdAt,
    required String email,
    String? id,
    String? ip,
    String? source,
  }) : this._({
         'confirm_token': ?confirmToken,
         'confirmed_at': ?confirmedAt?.toUtc().toIso8601String(),
         'created_at': ?createdAt?.toUtc().toIso8601String(),
         'email': email,
         'id': ?id,
         'ip': ?ip,
         'source': ?source,
       });

  /// Returns a copy with `confirmed_at` set to SQL NULL, overriding any
  /// database default.
  WaitlistInsert setConfirmedAtToNull() =>
      WaitlistInsert._({..._json, 'confirmed_at': null});

  /// Returns a copy with `ip` set to SQL NULL, overriding any database default.
  WaitlistInsert setIpToNull() => WaitlistInsert._({..._json, 'ip': null});

  /// Returns a copy with `source` set to SQL NULL, overriding any database
  /// default.
  WaitlistInsert setSourceToNull() =>
      WaitlistInsert._({..._json, 'source': null});
}

/// Values for updating rows of `waitlist`. All columns are optional; passing
/// `null` omits the column, leaving it unchanged. Use the `set…ToNull` methods
/// to write SQL NULL explicitly.
extension type const WaitlistUpdate._(Map<String, dynamic> _json)
    implements Object {
  WaitlistUpdate({
    String? confirmToken,
    DateTime? confirmedAt,
    DateTime? createdAt,
    String? email,
    String? id,
    String? ip,
    String? source,
  }) : this._({
         'confirm_token': ?confirmToken,
         'confirmed_at': ?confirmedAt?.toUtc().toIso8601String(),
         'created_at': ?createdAt?.toUtc().toIso8601String(),
         'email': ?email,
         'id': ?id,
         'ip': ?ip,
         'source': ?source,
       });

  /// Returns a copy with `confirmed_at` set to SQL NULL, overriding any
  /// database default.
  WaitlistUpdate setConfirmedAtToNull() =>
      WaitlistUpdate._({..._json, 'confirmed_at': null});

  /// Returns a copy with `ip` set to SQL NULL, overriding any database default.
  WaitlistUpdate setIpToNull() => WaitlistUpdate._({..._json, 'ip': null});

  /// Returns a copy with `source` set to SQL NULL, overriding any database
  /// default.
  WaitlistUpdate setSourceToNull() =>
      WaitlistUpdate._({..._json, 'source': null});
}

/// Typed access to the `waitlist` table.
class Waitlist {
  const Waitlist._();

  /// Table definition for [PostgrestClient.table].
  static const table =
      PostgrestTable<WaitlistRow, WaitlistInsert, WaitlistUpdate>(
        'waitlist',
        WaitlistRow.new,
        schema: 'public',
        primaryKey: [id],
      );

  static const confirmToken = PostgrestColumn<WaitlistRow, String>(
    'confirm_token',
  );
  static const confirmedAt = PostgrestNullableColumn<WaitlistRow, DateTime>(
    'confirmed_at',
  );
  static const createdAt = PostgrestColumn<WaitlistRow, DateTime>('created_at');
  static const email = PostgrestColumn<WaitlistRow, String>('email');
  static const id = PostgrestColumn<WaitlistRow, String>('id');
  static const ip = PostgrestNullableColumn<WaitlistRow, String>('ip');
  static const source = PostgrestNullableColumn<WaitlistRow, String>('source');
}
