// coverage:ignore-file
// Generated by flutter gen-l10n from the ARB files in l10n (ADR 0020), so
// the tests of the screens that show each string cover it, not this file.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;

import 'auth_localizations.dart';

// ignore_for_file: type=lint

/// The translations for German (`de`).
class AuthLocalizationsDe extends AuthLocalizations {
  AuthLocalizationsDe([String locale = 'de']) : super(locale);

  @override
  String get signUpTitle => 'Fast geschafft';

  @override
  String signUpTitleWithName(String name) {
    return 'Fast geschafft, $name';
  }

  @override
  String get signUpBody =>
      'Leg dein Konto an, damit deine Reflexionen sicher bleiben – und auf jedem Handy bei dir sind.';

  @override
  String get signInTitle => 'Willkommen zurück';

  @override
  String get privacyNoticeButton => 'Datenschutzerklärung';

  @override
  String get appleButton => 'Mit Apple fortfahren';

  @override
  String get googleButton => 'Weiter mit Google';

  @override
  String get lastUsedTag => 'Zuletzt genutzt';

  @override
  String lastUsedButton(String button) {
    return '$button, zuletzt genutzt';
  }

  @override
  String get orWithEmail => 'oder mit deiner E-Mail';

  @override
  String get emailLabel => 'E-Mail-Adresse';

  @override
  String get emailHint => 'du@example.com';

  @override
  String get sendCodeButton => 'Schick mir einen Code';

  @override
  String codeSentMessage(String email) {
    return 'Wir haben dir einen Code an $email geschickt.';
  }

  @override
  String get codeLabel => 'Code';

  @override
  String passwordPrompt(String email) {
    return 'Gib das Passwort für $email ein.';
  }

  @override
  String get passwordLabel => 'Passwort';

  @override
  String get signInButton => 'Anmelden';

  @override
  String get changeEmailButton => 'Andere E-Mail-Adresse nutzen';

  @override
  String get tooManyCodesMessage =>
      'Es wurden zu viele Codes angefordert. Bitte versuch es später noch einmal.';

  @override
  String get tooManyAttemptsMessage =>
      'Zu viele Versuche. Warte ein paar Minuten und versuch es dann noch einmal.';

  @override
  String get couldNotSendMessage =>
      'An diese Adresse konnte kein Code gehen. Prüfe sie und versuch es noch einmal.';

  @override
  String get wrongCodeMessage =>
      'Dieser Code ist falsch oder abgelaufen. Fordere bei Bedarf einen neuen an.';

  @override
  String get wrongPasswordMessage => 'Dieses Passwort wurde nicht angenommen.';

  @override
  String get unreachableMessage =>
      'Der Anmeldedienst ist gerade nicht erreichbar.';

  @override
  String get noAccountMessage =>
      'Diese E-Mail-Adresse kenne ich noch nicht – tippe auf „Los geht’s“, um zu beginnen.';

  @override
  String get providerFailedMessage =>
      'Diese Anmeldung hat nicht geklappt. Versuch es noch einmal oder nimm deine E-Mail-Adresse.';
}
