// coverage:ignore-file
// Generated by flutter gen-l10n from the ARB files in l10n (ADR 0020), so
// the tests of the screens that show each string cover it, not this file.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;

import 'auth_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AuthLocalizationsEn extends AuthLocalizations {
  AuthLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get signUpTitle => 'Almost there';

  @override
  String signUpTitleWithName(String name) {
    return 'Almost there, $name';
  }

  @override
  String get signUpBody =>
      'Create your account so your reflections stay safe – and with you on any phone.';

  @override
  String get signInTitle => 'Welcome back';

  @override
  String get privacyNoticeButton => 'Privacy notice';

  @override
  String get appleButton => 'Continue with Apple';

  @override
  String get googleButton => 'Continue with Google';

  @override
  String get lastUsedTag => 'Last used';

  @override
  String lastUsedButton(String button) {
    return '$button, last used';
  }

  @override
  String get orWithEmail => 'or with your email';

  @override
  String get emailLabel => 'Email address';

  @override
  String get emailHint => 'you@example.com';

  @override
  String get passwordLabel => 'Password';

  @override
  String get newPasswordLabel => 'New password';

  @override
  String passwordRule(int count) {
    return 'At least $count characters';
  }

  @override
  String get showPassword => 'Show password';

  @override
  String get hidePassword => 'Hide password';

  @override
  String get signInButton => 'Sign in';

  @override
  String get createAccountButton => 'Create account';

  @override
  String get forgotPasswordButton => 'Forgot password?';

  @override
  String confirmationSentMessage(String email) {
    return 'We sent a code to $email. Enter it to confirm your address and open your account.';
  }

  @override
  String resetSentMessage(String email) {
    return 'If there is an account for $email, we sent it a code. Enter the code and choose a new password.';
  }

  @override
  String get codeLabel => 'Code';

  @override
  String get confirmButton => 'Confirm';

  @override
  String get savePasswordButton => 'Save password';

  @override
  String get resendCodeButton => 'Send a new code';

  @override
  String get codeResentMessage => 'A new code is on its way.';

  @override
  String newPasswordPrompt(String email) {
    return 'Choose a new password for $email.';
  }

  @override
  String get changeEmailButton => 'Use a different email';

  @override
  String get tooManyCodesMessage =>
      'Too many codes were requested. Please try again later.';

  @override
  String get tooManyAttemptsMessage =>
      'Too many attempts. Wait a few minutes and try again.';

  @override
  String get couldNotSendMessage =>
      'Could not send a mail to that address. Check it and try again.';

  @override
  String get wrongCodeMessage =>
      'That code is wrong or has expired. Send a new one if needed.';

  @override
  String get wrongPasswordMessage =>
      'That email and password don’t match an account. Check both, or reset your password.';

  @override
  String weakPasswordMessage(int count) {
    return 'That password is too short. Use at least $count characters.';
  }

  @override
  String get accountExistsMessage =>
      'There is already an account for this email. Enter its password, or reset it.';

  @override
  String get passwordNotSavedMessage =>
      'Your new password could not be saved. Try again.';

  @override
  String get unreachableMessage => 'Could not reach the sign-in service.';

  @override
  String get providerFailedMessage =>
      'That sign-in did not go through. Try again, or use your email.';

  @override
  String get humanCheckFailedMessage =>
      'I couldn’t confirm that a person is asking. Try again in a moment.';
}
