// coverage:ignore-file
// Generated by flutter gen-l10n from the ARB files in l10n (ADR 0020), so
// the tests of the screens that show each string cover it, not this file.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;

import 'auth_localizations.dart';

// ignore_for_file: type=lint

/// The translations for German (`de`).
class AuthLocalizationsDe extends AuthLocalizations {
  AuthLocalizationsDe([String locale = 'de']) : super(locale);

  @override
  String get signUpTitle => 'Fast geschafft';

  @override
  String signUpTitleWithName(String name) {
    return 'Fast geschafft, $name';
  }

  @override
  String get signUpBody =>
      'Leg dein Konto an, damit deine Reflexionen sicher bleiben – und auf jedem Handy bei dir sind.';

  @override
  String get signInTitle => 'Willkommen zurück';

  @override
  String get privacyNoticeButton => 'Datenschutzerklärung';

  @override
  String get appleButton => 'Mit Apple fortfahren';

  @override
  String get googleButton => 'Weiter mit Google';

  @override
  String get lastUsedTag => 'Zuletzt genutzt';

  @override
  String lastUsedButton(String button) {
    return '$button, zuletzt genutzt';
  }

  @override
  String get orWithEmail => 'oder mit deiner E-Mail';

  @override
  String get emailLabel => 'E-Mail-Adresse';

  @override
  String get emailHint => 'du@example.com';

  @override
  String get passwordLabel => 'Passwort';

  @override
  String get newPasswordLabel => 'Neues Passwort';

  @override
  String passwordRule(int count) {
    return 'Mindestens $count Zeichen';
  }

  @override
  String get showPassword => 'Passwort anzeigen';

  @override
  String get hidePassword => 'Passwort verbergen';

  @override
  String get signInButton => 'Anmelden';

  @override
  String get createAccountButton => 'Konto anlegen';

  @override
  String get forgotPasswordButton => 'Passwort vergessen?';

  @override
  String confirmationSentMessage(String email) {
    return 'Wir haben dir einen Code an $email geschickt. Gib ihn ein, um deine Adresse zu bestätigen und dein Konto zu öffnen.';
  }

  @override
  String resetSentMessage(String email) {
    return 'Wenn zu $email ein Konto gehört, haben wir dorthin einen Code geschickt. Gib den Code ein und wähle ein neues Passwort.';
  }

  @override
  String get codeLabel => 'Code';

  @override
  String get confirmButton => 'Bestätigen';

  @override
  String get savePasswordButton => 'Passwort speichern';

  @override
  String get resendCodeButton => 'Neuen Code senden';

  @override
  String get codeResentMessage => 'Ein neuer Code ist unterwegs.';

  @override
  String newPasswordPrompt(String email) {
    return 'Wähle ein neues Passwort für $email.';
  }

  @override
  String get changeEmailButton => 'Andere E-Mail-Adresse nutzen';

  @override
  String get tooManyCodesMessage =>
      'Es wurden zu viele Codes angefordert. Bitte versuch es später noch einmal.';

  @override
  String get tooManyAttemptsMessage =>
      'Zu viele Versuche. Warte ein paar Minuten und versuch es dann noch einmal.';

  @override
  String get couldNotSendMessage =>
      'An diese Adresse konnte keine Mail gehen. Prüfe sie und versuch es noch einmal.';

  @override
  String get wrongCodeMessage =>
      'Dieser Code ist falsch oder abgelaufen. Lass dir bei Bedarf einen neuen senden.';

  @override
  String get wrongPasswordMessage =>
      'E-Mail-Adresse und Passwort passen zu keinem Konto. Prüfe beides oder setze dein Passwort zurück.';

  @override
  String weakPasswordMessage(int count) {
    return 'Dieses Passwort ist zu kurz. Nimm mindestens $count Zeichen.';
  }

  @override
  String get accountExistsMessage =>
      'Zu dieser E-Mail-Adresse gibt es schon ein Konto. Gib sein Passwort ein oder setze es zurück.';

  @override
  String get passwordNotSavedMessage =>
      'Dein neues Passwort konnte nicht gespeichert werden. Versuch es noch einmal.';

  @override
  String get unreachableMessage =>
      'Der Anmeldedienst ist gerade nicht erreichbar.';

  @override
  String get providerFailedMessage =>
      'Diese Anmeldung hat nicht geklappt. Versuch es noch einmal oder nimm deine E-Mail-Adresse.';

  @override
  String get humanCheckFailedMessage =>
      'Ich konnte nicht bestätigen, dass ein Mensch fragt. Versuch es gleich noch einmal.';
}
