// coverage:ignore-file
// Generated by flutter gen-l10n from the ARB files in l10n (ADR 0020), so
// the tests of the screens that show each string cover it, not this file.
import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:intl/intl.dart' as intl;

import 'auth_localizations_de.dart';
import 'auth_localizations_en.dart';

// ignore_for_file: type=lint

/// Callers can lookup localized strings with an instance of AuthLocalizations
/// returned by `AuthLocalizations.of(context)`.
///
/// Applications need to include `AuthLocalizations.delegate()` in their app's
/// `localizationDelegates` list, and the locales they support in the app's
/// `supportedLocales` list. For example:
///
/// ```dart
/// import 'l10n/auth_localizations.dart';
///
/// return MaterialApp(
///   localizationsDelegates: AuthLocalizations.localizationsDelegates,
///   supportedLocales: AuthLocalizations.supportedLocales,
///   home: MyApplicationHome(),
/// );
/// ```
///
/// ## Update pubspec.yaml
///
/// Please make sure to update your pubspec.yaml to include the following
/// packages:
///
/// ```yaml
/// dependencies:
///   # Internationalization support.
///   flutter_localizations:
///     sdk: flutter
///   intl: any # Use the pinned version from flutter_localizations
///
///   # Rest of dependencies
/// ```
///
/// ## iOS Applications
///
/// iOS applications define key application metadata, including supported
/// locales, in an Info.plist file that is built into the application bundle.
/// To configure the locales supported by your app, you’ll need to edit this
/// file.
///
/// First, open your project’s ios/Runner.xcworkspace Xcode workspace file.
/// Then, in the Project Navigator, open the Info.plist file under the Runner
/// project’s Runner folder.
///
/// Next, select the Information Property List item, select Add Item from the
/// Editor menu, then select Localizations from the pop-up menu.
///
/// Select and expand the newly-created Localizations item then, for each
/// locale your application supports, add a new item and select the locale
/// you wish to add from the pop-up menu in the Value field. This list should
/// be consistent with the languages listed in the AuthLocalizations.supportedLocales
/// property.
abstract class AuthLocalizations {
  AuthLocalizations(String locale)
    : localeName = intl.Intl.canonicalizedLocale(locale.toString());

  final String localeName;

  static AuthLocalizations of(BuildContext context) {
    return Localizations.of<AuthLocalizations>(context, AuthLocalizations)!;
  }

  static const LocalizationsDelegate<AuthLocalizations> delegate =
      _AuthLocalizationsDelegate();

  /// A list of this localizations delegate along with the default localizations
  /// delegates.
  ///
  /// Returns a list of localizations delegates containing this delegate along with
  /// GlobalMaterialLocalizations.delegate, GlobalCupertinoLocalizations.delegate,
  /// and GlobalWidgetsLocalizations.delegate.
  ///
  /// Additional delegates can be added by appending to this list in
  /// MaterialApp. This list does not have to be used at all if a custom list
  /// of delegates is preferred or required.
  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates =
      <LocalizationsDelegate<dynamic>>[
        delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ];

  /// A list of this localizations delegate's supported locales.
  static const List<Locale> supportedLocales = <Locale>[
    Locale('en'),
    Locale('de'),
  ];

  /// Sign-in screen heading when it is the last step of onboarding and the user skipped telling us their name. The account is about to be created.
  ///
  /// In en, this message translates to:
  /// **'Almost there'**
  String get signUpTitle;

  /// Sign-in screen heading when it is the last step of onboarding, greeting the user by the name they typed a step earlier. The account is about to be created.
  ///
  /// In en, this message translates to:
  /// **'Almost there, {name}'**
  String signUpTitleWithName(String name);

  /// Sign-in screen, last step of onboarding: under the heading, why the user should create an account now. "Reflections" are the user's journal entries.
  ///
  /// In en, this message translates to:
  /// **'Create your account so your reflections stay safe – and with you on any phone.'**
  String get signUpBody;

  /// Sign-in screen heading when a returning user tapped "I have an account" on the welcome screen.
  ///
  /// In en, this message translates to:
  /// **'Welcome back'**
  String get signInTitle;

  /// Sign-in screen, link at the bottom that opens emotely's privacy notice in the browser, reachable before an account exists.
  ///
  /// In en, this message translates to:
  /// **'Privacy notice'**
  String get privacyNoticeButton;

  /// Sign-in screen, iOS only: the title of the Sign in with Apple button, after Apple's logo. Apple allows only its own titles: use Apple's official translation of "Continue with Apple" in the target language, never a free one.
  ///
  /// In en, this message translates to:
  /// **'Continue with Apple'**
  String get appleButton;

  /// Sign-in screen: the title of the Sign in with Google button, after Google's "G". Google allows only its own labels: use Google's official translation of "Continue with Google" in the target language, never a free one.
  ///
  /// In en, this message translates to:
  /// **'Continue with Google'**
  String get googleButton;

  /// Sign-in screen: a small pill on the edge of the sign-in button the user used last on this phone (Apple, Google or the email and password), to remind them which one they picked. Keep it very short.
  ///
  /// In en, this message translates to:
  /// **'Last used'**
  String get lastUsedTag;

  /// Sign-in screen: what a screen reader announces for the sign-in button the user used last on this phone, the button's own label followed by the "Last used" pill's words.
  ///
  /// In en, this message translates to:
  /// **'{button}, last used'**
  String lastUsedButton(String button);

  /// Sign-in screen: a small label in a horizontal rule between the Apple and Google buttons above and the email and password fields below. Lower case: it continues the buttons above it.
  ///
  /// In en, this message translates to:
  /// **'or with your email'**
  String get orWithEmail;

  /// Sign-in screen: the label of the field for the account's email address.
  ///
  /// In en, this message translates to:
  /// **'Email address'**
  String get emailLabel;

  /// Sign-in screen: the example shown in the empty email field. Keep the reserved domain example.com; only the part before the @ may change, to the target language's "you".
  ///
  /// In en, this message translates to:
  /// **'you@example.com'**
  String get emailHint;

  /// Sign-in screen: the label of the password field, under the email field, both when signing in and when creating an account.
  ///
  /// In en, this message translates to:
  /// **'Password'**
  String get passwordLabel;

  /// Sign-in screen, resetting a forgotten password: the label of the field for the password the account will have from now on.
  ///
  /// In en, this message translates to:
  /// **'New password'**
  String get newPasswordLabel;

  /// Sign-in screen: the help line under a password field whenever the user chooses a password (a new account, a reset). There is no other rule: any characters count.
  ///
  /// In en, this message translates to:
  /// **'At least {count} characters'**
  String passwordRule(int count);

  /// Sign-in screen: what a screen reader announces for the eye button at the end of a password field, which shows the password as typed.
  ///
  /// In en, this message translates to:
  /// **'Show password'**
  String get showPassword;

  /// Sign-in screen: what a screen reader announces for the eye button at the end of a password field while the password is shown, which hides it again.
  ///
  /// In en, this message translates to:
  /// **'Hide password'**
  String get hidePassword;

  /// Sign-in screen, "I have an account": the button under the email and password that signs in.
  ///
  /// In en, this message translates to:
  /// **'Sign in'**
  String get signInButton;

  /// Sign-in screen, last step of onboarding: the button under the email and password that creates the account. A code to confirm the address is mailed next.
  ///
  /// In en, this message translates to:
  /// **'Create account'**
  String get createAccountButton;

  /// Sign-in screen: a small button under the sign-in button that mails a code to the address typed above, to choose a new password.
  ///
  /// In en, this message translates to:
  /// **'Forgot password?'**
  String get forgotPasswordButton;

  /// Sign-in screen, after creating an account: tells the user a six-digit code is on its way to their address, above the field to type it into. The account opens once the code is typed.
  ///
  /// In en, this message translates to:
  /// **'We sent a code to {email}. Enter it to confirm your address and open your account.'**
  String confirmationSentMessage(String email);

  /// Sign-in screen, after "Forgot password?": a six-digit code is on its way if the address has an account (the screen cannot know), above the fields for the code and the new password.
  ///
  /// In en, this message translates to:
  /// **'If there is an account for {email}, we sent it a code. Enter the code and choose a new password.'**
  String resetSentMessage(String email);

  /// Sign-in screen: the label of the field for the six-digit code from the email.
  ///
  /// In en, this message translates to:
  /// **'Code'**
  String get codeLabel;

  /// Sign-in screen, after creating an account: button that checks the code just typed and opens the account.
  ///
  /// In en, this message translates to:
  /// **'Confirm'**
  String get confirmButton;

  /// Sign-in screen, resetting a forgotten password: button that saves the new password and signs in.
  ///
  /// In en, this message translates to:
  /// **'Save password'**
  String get savePasswordButton;

  /// Sign-in screen, at a code step: button that mails a fresh code, for a mail that did not arrive or a code that expired.
  ///
  /// In en, this message translates to:
  /// **'Send a new code'**
  String get resendCodeButton;

  /// Sign-in screen, at a code step: confirms that "Send a new code" worked.
  ///
  /// In en, this message translates to:
  /// **'A new code is on its way.'**
  String get codeResentMessage;

  /// Sign-in screen, resetting a forgotten password: shown when the code was right but the new password could not be saved, so the user picks it once more.
  ///
  /// In en, this message translates to:
  /// **'Choose a new password for {email}.'**
  String newPasswordPrompt(String email);

  /// Sign-in screen, at a code step: button that goes back to the email and password to type another address.
  ///
  /// In en, this message translates to:
  /// **'Use a different email'**
  String get changeEmailButton;

  /// Sign-in screen error: the sign-in service refused to mail another code because too many were sent recently.
  ///
  /// In en, this message translates to:
  /// **'Too many codes were requested. Please try again later.'**
  String get tooManyCodesMessage;

  /// Sign-in screen error, any step: the sign-in service is rate-limiting this device. What the user typed may well be right, so it must not sound like a wrong code or password.
  ///
  /// In en, this message translates to:
  /// **'Too many attempts. Wait a few minutes and try again.'**
  String get tooManyAttemptsMessage;

  /// Sign-in screen error: the sign-in service refused to mail the address typed (to create an account, or for a code), most likely because it is not a real address.
  ///
  /// In en, this message translates to:
  /// **'Could not send a mail to that address. Check it and try again.'**
  String get couldNotSendMessage;

  /// Sign-in screen error, at a code step: the six-digit code the user typed was not accepted. "Send a new one" points at the "Send a new code" button.
  ///
  /// In en, this message translates to:
  /// **'That code is wrong or has expired. Send a new one if needed.'**
  String get wrongCodeMessage;

  /// Sign-in screen error: the email and password did not sign in. The service does not say which of the two is wrong, so neither may be blamed alone. "Reset your password" points at "Forgot password?".
  ///
  /// In en, this message translates to:
  /// **'That email and password don’t match an account. Check both, or reset your password.'**
  String get wrongPasswordMessage;

  /// Sign-in screen error: the sign-in service refused a new password as too weak.
  ///
  /// In en, this message translates to:
  /// **'That password is too short. Use at least {count} characters.'**
  String weakPasswordMessage(int count);

  /// Sign-in screen error, last step of onboarding: the user tried to create an account for an address that has one, and the password typed is not that account's. "Reset it" points at "Forgot password?".
  ///
  /// In en, this message translates to:
  /// **'There is already an account for this email. Enter its password, or reset it.'**
  String get accountExistsMessage;

  /// Sign-in screen error, resetting a forgotten password: the code was right, but saving the new password failed.
  ///
  /// In en, this message translates to:
  /// **'Your new password could not be saved. Try again.'**
  String get passwordNotSavedMessage;

  /// Sign-in screen error, any step: no answer from the sign-in service at all (offline, timeout).
  ///
  /// In en, this message translates to:
  /// **'Could not reach the sign-in service.'**
  String get unreachableMessage;

  /// Sign-in screen error: signing in with Apple or Google failed (not a dismissal). The email and password below are the other way in.
  ///
  /// In en, this message translates to:
  /// **'That sign-in did not go through. Try again, or use your email.'**
  String get providerFailedMessage;

  /// Sign-in screen error: the invisible security check that runs before an account is created, a password is checked or a code is mailed (Cloudflare Turnstile) failed, or the sign-in service refused its result. Nothing the user typed is wrong, so it must not sound like a wrong address or password; trying again runs a fresh check. emotely speaks as "I".
  ///
  /// In en, this message translates to:
  /// **'I couldn’t confirm that a person is asking. Try again in a moment.'**
  String get humanCheckFailedMessage;
}

class _AuthLocalizationsDelegate
    extends LocalizationsDelegate<AuthLocalizations> {
  const _AuthLocalizationsDelegate();

  @override
  Future<AuthLocalizations> load(Locale locale) {
    return SynchronousFuture<AuthLocalizations>(
      lookupAuthLocalizations(locale),
    );
  }

  @override
  bool isSupported(Locale locale) =>
      <String>['de', 'en'].contains(locale.languageCode);

  @override
  bool shouldReload(_AuthLocalizationsDelegate old) => false;
}

AuthLocalizations lookupAuthLocalizations(Locale locale) {
  // Lookup logic when only language code is specified.
  switch (locale.languageCode) {
    case 'de':
      return AuthLocalizationsDe();
    case 'en':
      return AuthLocalizationsEn();
  }

  throw FlutterError(
    'AuthLocalizations.delegate failed to load unsupported locale "$locale". This is likely '
    'an issue with the localizations generation tool. Please file an issue '
    'on GitHub with a reproducible sample app and the gen-l10n configuration '
    'that was used.',
  );
}
