// coverage:ignore-file
// Generated by flutter gen-l10n from the ARB files in l10n (ADR 0020), so
// the tests of the screens that show each string cover it, not this file.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;

import 'auth_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AuthLocalizationsEn extends AuthLocalizations {
  AuthLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get signUpTitle => 'Almost there';

  @override
  String signUpTitleWithName(String name) {
    return 'Almost there, $name';
  }

  @override
  String get signUpBody =>
      'Create your account so your reflections stay safe – and with you on any phone.';

  @override
  String get signInTitle => 'Welcome back';

  @override
  String get privacyNoticeButton => 'Privacy notice';

  @override
  String get appleButton => 'Continue with Apple';

  @override
  String get googleButton => 'Sign in with Google';

  @override
  String get lastUsedTag => 'Last used';

  @override
  String lastUsedButton(String button) {
    return '$button, last used';
  }

  @override
  String get orWithEmail => 'or with your email';

  @override
  String get emailLabel => 'Email address';

  @override
  String get emailHint => 'you@example.com';

  @override
  String get sendCodeButton => 'Send me a code';

  @override
  String codeSentMessage(String email) {
    return 'We sent a code to $email.';
  }

  @override
  String get codeLabel => 'Code';

  @override
  String passwordPrompt(String email) {
    return 'Enter the password for $email.';
  }

  @override
  String get passwordLabel => 'Password';

  @override
  String get signInButton => 'Sign in';

  @override
  String get changeEmailButton => 'Use a different email';

  @override
  String get tooManyCodesMessage =>
      'Too many codes were requested. Please try again later.';

  @override
  String get tooManyAttemptsMessage =>
      'Too many attempts. Wait a few minutes and try again.';

  @override
  String get couldNotSendMessage =>
      'Could not send a code to that email. Check the address and try again.';

  @override
  String get wrongCodeMessage =>
      'That code is wrong or has expired. Request a new one if needed.';

  @override
  String get wrongPasswordMessage => 'That password was not accepted.';

  @override
  String get unreachableMessage => 'Could not reach the sign-in service.';

  @override
  String get noAccountMessage =>
      'I don’t know this email yet – tap Get started to begin.';

  @override
  String get providerFailedMessage =>
      'That sign-in did not go through. Try again, or use your email.';
}
