// coverage:ignore-file
// Generated by flutter gen-l10n from the ARB files in l10n (ADR 0020), so
// the tests of the screens that show each string cover it, not this file.
import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:intl/intl.dart' as intl;

import 'auth_localizations_de.dart';
import 'auth_localizations_en.dart';

// ignore_for_file: type=lint

/// Callers can lookup localized strings with an instance of AuthLocalizations
/// returned by `AuthLocalizations.of(context)`.
///
/// Applications need to include `AuthLocalizations.delegate()` in their app's
/// `localizationDelegates` list, and the locales they support in the app's
/// `supportedLocales` list. For example:
///
/// ```dart
/// import 'l10n/auth_localizations.dart';
///
/// return MaterialApp(
///   localizationsDelegates: AuthLocalizations.localizationsDelegates,
///   supportedLocales: AuthLocalizations.supportedLocales,
///   home: MyApplicationHome(),
/// );
/// ```
///
/// ## Update pubspec.yaml
///
/// Please make sure to update your pubspec.yaml to include the following
/// packages:
///
/// ```yaml
/// dependencies:
///   # Internationalization support.
///   flutter_localizations:
///     sdk: flutter
///   intl: any # Use the pinned version from flutter_localizations
///
///   # Rest of dependencies
/// ```
///
/// ## iOS Applications
///
/// iOS applications define key application metadata, including supported
/// locales, in an Info.plist file that is built into the application bundle.
/// To configure the locales supported by your app, you’ll need to edit this
/// file.
///
/// First, open your project’s ios/Runner.xcworkspace Xcode workspace file.
/// Then, in the Project Navigator, open the Info.plist file under the Runner
/// project’s Runner folder.
///
/// Next, select the Information Property List item, select Add Item from the
/// Editor menu, then select Localizations from the pop-up menu.
///
/// Select and expand the newly-created Localizations item then, for each
/// locale your application supports, add a new item and select the locale
/// you wish to add from the pop-up menu in the Value field. This list should
/// be consistent with the languages listed in the AuthLocalizations.supportedLocales
/// property.
abstract class AuthLocalizations {
  AuthLocalizations(String locale)
    : localeName = intl.Intl.canonicalizedLocale(locale.toString());

  final String localeName;

  static AuthLocalizations of(BuildContext context) {
    return Localizations.of<AuthLocalizations>(context, AuthLocalizations)!;
  }

  static const LocalizationsDelegate<AuthLocalizations> delegate =
      _AuthLocalizationsDelegate();

  /// A list of this localizations delegate along with the default localizations
  /// delegates.
  ///
  /// Returns a list of localizations delegates containing this delegate along with
  /// GlobalMaterialLocalizations.delegate, GlobalCupertinoLocalizations.delegate,
  /// and GlobalWidgetsLocalizations.delegate.
  ///
  /// Additional delegates can be added by appending to this list in
  /// MaterialApp. This list does not have to be used at all if a custom list
  /// of delegates is preferred or required.
  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates =
      <LocalizationsDelegate<dynamic>>[
        delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ];

  /// A list of this localizations delegate's supported locales.
  static const List<Locale> supportedLocales = <Locale>[
    Locale('en'),
    Locale('de'),
  ];

  /// Sign-in screen heading when it is the last step of onboarding and the user skipped telling us their name. The account is about to be created.
  ///
  /// In en, this message translates to:
  /// **'Almost there'**
  String get signUpTitle;

  /// Sign-in screen heading when it is the last step of onboarding, greeting the user by the name they typed a step earlier. The account is about to be created.
  ///
  /// In en, this message translates to:
  /// **'Almost there, {name}'**
  String signUpTitleWithName(String name);

  /// Sign-in screen, last step of onboarding: under the heading, why the user should create an account now. "Reflections" are the user's journal entries.
  ///
  /// In en, this message translates to:
  /// **'Create your account so your reflections stay safe – and with you on any phone.'**
  String get signUpBody;

  /// Sign-in screen heading when a returning user tapped "I have an account" on the welcome screen.
  ///
  /// In en, this message translates to:
  /// **'Welcome back'**
  String get signInTitle;

  /// Sign-in screen, link at the bottom that opens emotely's privacy notice in the browser, reachable before an account exists.
  ///
  /// In en, this message translates to:
  /// **'Privacy notice'**
  String get privacyNoticeButton;

  /// Sign-in screen, iOS only: the label of Apple's own sign-in button. Use Apple's official wording for "Continue with Apple" in the target language.
  ///
  /// In en, this message translates to:
  /// **'Continue with Apple'**
  String get appleButton;

  /// Sign-in screen: what a screen reader announces for Google's sign-in button. The button itself is Google's image with its label baked in, in English; use Google's official wording for "Sign in with Google" in the target language.
  ///
  /// In en, this message translates to:
  /// **'Sign in with Google'**
  String get googleButton;

  /// Sign-in screen: a small pill on the edge of the sign-in button the user used last on this phone (Apple, Google or the email code), to remind them which one they picked. Keep it very short.
  ///
  /// In en, this message translates to:
  /// **'Last used'**
  String get lastUsedTag;

  /// Sign-in screen: what a screen reader announces for the sign-in button the user used last on this phone, the button's own label followed by the "Last used" pill's words.
  ///
  /// In en, this message translates to:
  /// **'{button}, last used'**
  String lastUsedButton(String button);

  /// Sign-in screen: a small label in a horizontal rule between the Apple and Google buttons above and the email field below. Lower case: it continues the buttons above it.
  ///
  /// In en, this message translates to:
  /// **'or with your email'**
  String get orWithEmail;

  /// Sign-in screen, first step: the label of the field for the email address a sign-in code is sent to.
  ///
  /// In en, this message translates to:
  /// **'Email address'**
  String get emailLabel;

  /// Sign-in screen, first step: the example shown in the empty email field. Keep the reserved domain example.com; only the part before the @ may change, to the target language's "you".
  ///
  /// In en, this message translates to:
  /// **'you@example.com'**
  String get emailHint;

  /// Sign-in screen, first step: button that emails a six-digit sign-in code to the address typed above it.
  ///
  /// In en, this message translates to:
  /// **'Send me a code'**
  String get sendCodeButton;

  /// Sign-in screen, second step: tells the user a six-digit code is on its way to their address, above the field to type it into.
  ///
  /// In en, this message translates to:
  /// **'We sent a code to {email}.'**
  String codeSentMessage(String email);

  /// Sign-in screen, second step: the label of the field for the six-digit code from the email.
  ///
  /// In en, this message translates to:
  /// **'Code'**
  String get codeLabel;

  /// Sign-in screen, second step for the app stores' review accounts only: asks for the account's password instead of a code.
  ///
  /// In en, this message translates to:
  /// **'Enter the password for {email}.'**
  String passwordPrompt(String email);

  /// Sign-in screen, second step for the app stores' review accounts: the label of the password field.
  ///
  /// In en, this message translates to:
  /// **'Password'**
  String get passwordLabel;

  /// Sign-in screen, second step: button that signs in with the code (or the review account's password) just typed.
  ///
  /// In en, this message translates to:
  /// **'Sign in'**
  String get signInButton;

  /// Sign-in screen, second step: button that goes back to the first step to type another email address.
  ///
  /// In en, this message translates to:
  /// **'Use a different email'**
  String get changeEmailButton;

  /// Sign-in screen error, first step: the sign-in service refused to send another code because too many were sent recently.
  ///
  /// In en, this message translates to:
  /// **'Too many codes were requested. Please try again later.'**
  String get tooManyCodesMessage;

  /// Sign-in screen error, any step: the sign-in service is rate-limiting this device. What the user typed may well be right, so it must not sound like a wrong code or password.
  ///
  /// In en, this message translates to:
  /// **'Too many attempts. Wait a few minutes and try again.'**
  String get tooManyAttemptsMessage;

  /// Sign-in screen error, first step: the sign-in service refused to send a code to the address typed, most likely because it is not a real address.
  ///
  /// In en, this message translates to:
  /// **'Could not send a code to that email. Check the address and try again.'**
  String get couldNotSendMessage;

  /// Sign-in screen error, second step: the six-digit code the user typed did not sign them in.
  ///
  /// In en, this message translates to:
  /// **'That code is wrong or has expired. Request a new one if needed.'**
  String get wrongCodeMessage;

  /// Sign-in screen error, second step for the app stores' review accounts: the password did not sign them in.
  ///
  /// In en, this message translates to:
  /// **'That password was not accepted.'**
  String get wrongPasswordMessage;

  /// Sign-in screen error, any step: no answer from the sign-in service at all (offline, timeout).
  ///
  /// In en, this message translates to:
  /// **'Could not reach the sign-in service.'**
  String get unreachableMessage;

  /// Sign-in screen error, first step, for a returning user: there is no account for this address. emotely speaks as "I". "Get started" is the welcome screen's first button, which begins onboarding; quote it exactly as that button is translated.
  ///
  /// In en, this message translates to:
  /// **'I don’t know this email yet – tap Get started to begin.'**
  String get noAccountMessage;

  /// Sign-in screen error, first step: signing in with Apple or Google failed (not a dismissal). The email code below is the other way in.
  ///
  /// In en, this message translates to:
  /// **'That sign-in did not go through. Try again, or use your email.'**
  String get providerFailedMessage;
}

class _AuthLocalizationsDelegate
    extends LocalizationsDelegate<AuthLocalizations> {
  const _AuthLocalizationsDelegate();

  @override
  Future<AuthLocalizations> load(Locale locale) {
    return SynchronousFuture<AuthLocalizations>(
      lookupAuthLocalizations(locale),
    );
  }

  @override
  bool isSupported(Locale locale) =>
      <String>['de', 'en'].contains(locale.languageCode);

  @override
  bool shouldReload(_AuthLocalizationsDelegate old) => false;
}

AuthLocalizations lookupAuthLocalizations(Locale locale) {
  // Lookup logic when only language code is specified.
  switch (locale.languageCode) {
    case 'de':
      return AuthLocalizationsDe();
    case 'en':
      return AuthLocalizationsEn();
  }

  throw FlutterError(
    'AuthLocalizations.delegate failed to load unsupported locale "$locale". This is likely '
    'an issue with the localizations generation tool. Please file an issue '
    'on GitHub with a reproducible sample app and the gen-l10n configuration '
    'that was used.',
  );
}
