// coverage:ignore-file
// Generated by flutter gen-l10n from the ARB files in l10n (ADR 0020), so
// the tests of the screens that show each string cover it, not this file.
import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:intl/intl.dart' as intl;

import 'session_localizations_de.dart';
import 'session_localizations_en.dart';

// ignore_for_file: type=lint

/// Callers can lookup localized strings with an instance of SessionLocalizations
/// returned by `SessionLocalizations.of(context)`.
///
/// Applications need to include `SessionLocalizations.delegate()` in their app's
/// `localizationDelegates` list, and the locales they support in the app's
/// `supportedLocales` list. For example:
///
/// ```dart
/// import 'l10n/session_localizations.dart';
///
/// return MaterialApp(
///   localizationsDelegates: SessionLocalizations.localizationsDelegates,
///   supportedLocales: SessionLocalizations.supportedLocales,
///   home: MyApplicationHome(),
/// );
/// ```
///
/// ## Update pubspec.yaml
///
/// Please make sure to update your pubspec.yaml to include the following
/// packages:
///
/// ```yaml
/// dependencies:
///   # Internationalization support.
///   flutter_localizations:
///     sdk: flutter
///   intl: any # Use the pinned version from flutter_localizations
///
///   # Rest of dependencies
/// ```
///
/// ## iOS Applications
///
/// iOS applications define key application metadata, including supported
/// locales, in an Info.plist file that is built into the application bundle.
/// To configure the locales supported by your app, you’ll need to edit this
/// file.
///
/// First, open your project’s ios/Runner.xcworkspace Xcode workspace file.
/// Then, in the Project Navigator, open the Info.plist file under the Runner
/// project’s Runner folder.
///
/// Next, select the Information Property List item, select Add Item from the
/// Editor menu, then select Localizations from the pop-up menu.
///
/// Select and expand the newly-created Localizations item then, for each
/// locale your application supports, add a new item and select the locale
/// you wish to add from the pop-up menu in the Value field. This list should
/// be consistent with the languages listed in the SessionLocalizations.supportedLocales
/// property.
abstract class SessionLocalizations {
  SessionLocalizations(String locale)
    : localeName = intl.Intl.canonicalizedLocale(locale.toString());

  final String localeName;

  static SessionLocalizations of(BuildContext context) {
    return Localizations.of<SessionLocalizations>(
      context,
      SessionLocalizations,
    )!;
  }

  static const LocalizationsDelegate<SessionLocalizations> delegate =
      _SessionLocalizationsDelegate();

  /// A list of this localizations delegate along with the default localizations
  /// delegates.
  ///
  /// Returns a list of localizations delegates containing this delegate along with
  /// GlobalMaterialLocalizations.delegate, GlobalCupertinoLocalizations.delegate,
  /// and GlobalWidgetsLocalizations.delegate.
  ///
  /// Additional delegates can be added by appending to this list in
  /// MaterialApp. This list does not have to be used at all if a custom list
  /// of delegates is preferred or required.
  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates =
      <LocalizationsDelegate<dynamic>>[
        delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ];

  /// A list of this localizations delegate's supported locales.
  static const List<Locale> supportedLocales = <Locale>[
    Locale('en'),
    Locale('de'),
  ];

  /// Session screen: app bar title while the journaling assistant asks its questions one by one and the user answers.
  ///
  /// In en, this message translates to:
  /// **'Journaling session'**
  String get sessionTitle;

  /// Session screen: shown under a spinner while the journaling assistant prepares its next question or writes the entry.
  ///
  /// In en, this message translates to:
  /// **'Thinking…'**
  String get thinkingLabel;

  /// Session screen: small label above the assistant's current question, counting the questions of this session from 1.
  ///
  /// In en, this message translates to:
  /// **'Question {number}'**
  String questionNumber(int number);

  /// Session screen failure: the app got no answer from the journaling assistant at all (offline, timed out). Shown above a Try again button.
  ///
  /// In en, this message translates to:
  /// **'Could not reach the journaling assistant.'**
  String get unreachableMessage;

  /// Session screen failure: the AI model behind the assistant is down on our side. It must say it is not the user's connection, that what they wrote is safe, and that waiting helps. Shown above a Try again button.
  ///
  /// In en, this message translates to:
  /// **'The journaling assistant is unavailable right now. This is not your connection, and your entry is safe. Please try again later.'**
  String get modelUnavailableMessage;

  /// Session screen failure: the assistant rejected this step for a reason a retry may fix. Nothing the user did wrong. Shown above a Try again button.
  ///
  /// In en, this message translates to:
  /// **'Something went wrong on our side. Please try again.'**
  String get refusedMessage;

  /// Session screen failure: this session can never be continued (for example it got too long), so only a fresh one helps. Reassures that earlier journal entries are untouched. Shown above the Start over button.
  ///
  /// In en, this message translates to:
  /// **'This session can no longer be continued. Start a new one; your saved entries are not affected.'**
  String get cannotContinueMessage;

  /// Session screen failure: the finished journal entry could not be stored. Shown above a Try again button.
  ///
  /// In en, this message translates to:
  /// **'Your entry could not be saved. Please try again.'**
  String get entrySaveFailedMessage;

  /// Session screen failure: the user reopened a session they had left half-way, and it could not be loaded. Shown above a Try again button.
  ///
  /// In en, this message translates to:
  /// **'Could not load your unfinished session. Please try again.'**
  String get sessionReadFailedMessage;

  /// Session screen button under the 'can no longer be continued' failure: discards this session and starts a new one.
  ///
  /// In en, this message translates to:
  /// **'Start over'**
  String get startOverButton;

  /// Session screen button under a failure message: repeats the step that failed.
  ///
  /// In en, this message translates to:
  /// **'Try again'**
  String get tryAgainButton;

  /// Session screen: button under every answer field (text, list, rating, colors, emoji) that sends the answer to the assistant. Disabled until there is an answer.
  ///
  /// In en, this message translates to:
  /// **'Submit'**
  String get submitButton;

  /// Session screen: placeholder in the empty multi-line field where the user answers a question in their own words.
  ///
  /// In en, this message translates to:
  /// **'Write freely…'**
  String get longtextHint;

  /// Session screen: placeholder in each field of a list answer, one short item per field (for example one thing they are grateful for). Writing in the last field opens the next.
  ///
  /// In en, this message translates to:
  /// **'Write one thing…'**
  String get textListHint;

  /// Session screen: small note under an answer that is close to the length limit, counting down the characters still allowed.
  ///
  /// In en, this message translates to:
  /// **'{count, plural, one{{count} character left} other{{count} characters left}}'**
  String answerLengthLeft(int count);

  /// Session screen: note in error colour under an answer that is over the length limit; the Submit button stays disabled until it is shortened.
  ///
  /// In en, this message translates to:
  /// **'{count, plural, one{{count} character too many. Shorten your answer to submit it.} other{{count} characters too many. Shorten your answer to submit it.}}'**
  String answerLengthOver(int count);

  /// Session screen, rating answer (a 1 to 10 slider): shown in place of the number while the slider rests on its leftmost stop, where nothing is chosen yet. Also read out by screen readers for that stop.
  ///
  /// In en, this message translates to:
  /// **'No answer'**
  String get ratingNoAnswer;

  /// Session screen, color answer: the screen-reader label of the empty circle that adds a color, and the title of the color picker dialog it opens.
  ///
  /// In en, this message translates to:
  /// **'Pick a color'**
  String get colorPickLabel;

  /// Color picker dialog: segment that shows a grid of ready-made color swatches (the Material primary colors).
  ///
  /// In en, this message translates to:
  /// **'Primary'**
  String get colorSwatchesTab;

  /// Color picker dialog: segment that shows a color wheel for picking any color freely.
  ///
  /// In en, this message translates to:
  /// **'Wheel'**
  String get colorWheelTab;

  /// Color picker dialog button: closes the dialog and changes nothing.
  ///
  /// In en, this message translates to:
  /// **'Cancel'**
  String get colorCancelButton;

  /// Color picker dialog button, only for a color already chosen: removes that color from the answer.
  ///
  /// In en, this message translates to:
  /// **'Clear'**
  String get colorClearButton;

  /// Color picker dialog button: puts the color shown in the picker into the answer.
  ///
  /// In en, this message translates to:
  /// **'Select'**
  String get colorSelectButton;

  /// Session screen, emoji answer: the screen-reader label of the empty tile that opens the emoji picker to add one.
  ///
  /// In en, this message translates to:
  /// **'Pick an emoji'**
  String get emojiPickLabel;

  /// Emoji picker sheet: screen-reader label of the button that removes the emoji the user tapped to change.
  ///
  /// In en, this message translates to:
  /// **'Clear emoji'**
  String get emojiClearLabel;

  /// Emoji picker sheet: placeholder in the search field, two example search words. Use words that find emoji in this language.
  ///
  /// In en, this message translates to:
  /// **'Smile, heart, …'**
  String get emojiSearchHint;

  /// Emoji picker sheet: shown in the 'recently used' tab before the user has picked any emoji.
  ///
  /// In en, this message translates to:
  /// **'No recent emoji'**
  String get emojiNoRecents;
}

class _SessionLocalizationsDelegate
    extends LocalizationsDelegate<SessionLocalizations> {
  const _SessionLocalizationsDelegate();

  @override
  Future<SessionLocalizations> load(Locale locale) {
    return SynchronousFuture<SessionLocalizations>(
      lookupSessionLocalizations(locale),
    );
  }

  @override
  bool isSupported(Locale locale) =>
      <String>['de', 'en'].contains(locale.languageCode);

  @override
  bool shouldReload(_SessionLocalizationsDelegate old) => false;
}

SessionLocalizations lookupSessionLocalizations(Locale locale) {
  // Lookup logic when only language code is specified.
  switch (locale.languageCode) {
    case 'de':
      return SessionLocalizationsDe();
    case 'en':
      return SessionLocalizationsEn();
  }

  throw FlutterError(
    'SessionLocalizations.delegate failed to load unsupported locale "$locale". This is likely '
    'an issue with the localizations generation tool. Please file an issue '
    'on GitHub with a reproducible sample app and the gen-l10n configuration '
    'that was used.',
  );
}
