// coverage:ignore-file
// Generated by flutter gen-l10n from the ARB files in l10n (ADR 0020), so
// the tests of the screens that show each string cover it, not this file.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;

import 'session_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class SessionLocalizationsEn extends SessionLocalizations {
  SessionLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get sessionTitle => 'Journaling session';

  @override
  String get thinkingLabel => 'Thinking…';

  @override
  String questionNumber(int number) {
    return 'Question $number';
  }

  @override
  String get unreachableMessage => 'Could not reach emotely.';

  @override
  String get modelUnavailableMessage =>
      'emotely is unavailable right now. This is not your connection, and your entry is safe. Please try again later.';

  @override
  String get refusedMessage =>
      'Something went wrong on our side. Please try again.';

  @override
  String get cannotContinueMessage =>
      'This session can no longer be continued. Start a new one; your saved entries are not affected.';

  @override
  String get entrySaveFailedMessage =>
      'Your entry could not be saved. Please try again.';

  @override
  String get sessionReadFailedMessage =>
      'Could not load your unfinished session. Please try again.';

  @override
  String get startOverButton => 'Start over';

  @override
  String get tryAgainButton => 'Try again';

  @override
  String get submitButton => 'Submit';

  @override
  String get longtextHint => 'Write freely…';

  @override
  String get textListHint => 'Write one thing…';

  @override
  String answerLengthLeft(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$count characters left',
      one: '$count character left',
    );
    return '$_temp0';
  }

  @override
  String answerLengthOver(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$count characters too many. Shorten your answer to submit it.',
      one: '$count character too many. Shorten your answer to submit it.',
    );
    return '$_temp0';
  }

  @override
  String get ratingNoAnswer => 'No answer';

  @override
  String get colorPickLabel => 'Pick a color';

  @override
  String get colorSwatchesTab => 'Primary';

  @override
  String get colorWheelTab => 'Wheel';

  @override
  String get colorCancelButton => 'Cancel';

  @override
  String get colorClearButton => 'Clear';

  @override
  String get colorSelectButton => 'Select';

  @override
  String get emojiPickLabel => 'Pick an emoji';

  @override
  String get emojiClearLabel => 'Clear emoji';

  @override
  String get emojiSearchHint => 'Smile, heart, …';

  @override
  String get emojiNoRecents => 'No recent emoji';
}
