// coverage:ignore-file
// Generated by flutter gen-l10n from the ARB files in l10n (ADR 0020), so
// the tests of the screens that show each string cover it, not this file.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;

import 'session_localizations.dart';

// ignore_for_file: type=lint

/// The translations for German (`de`).
class SessionLocalizationsDe extends SessionLocalizations {
  SessionLocalizationsDe([String locale = 'de']) : super(locale);

  @override
  String get sessionTitle => 'Tagebuch schreiben';

  @override
  String get thinkingLabel => 'Denkt nach…';

  @override
  String questionNumber(int number) {
    return 'Frage $number';
  }

  @override
  String get unreachableMessage => 'emotely ist gerade nicht erreichbar.';

  @override
  String get modelUnavailableMessage =>
      'emotely ist gerade nicht verfügbar. Das liegt nicht an deiner Verbindung, und dein Eintrag ist sicher. Bitte versuche es später noch einmal.';

  @override
  String get refusedMessage =>
      'Bei uns ist etwas schiefgelaufen. Bitte versuche es noch einmal.';

  @override
  String get cannotContinueMessage =>
      'Diese Session lässt sich nicht mehr fortsetzen. Beginne eine neue; deine gespeicherten Einträge bleiben davon unberührt.';

  @override
  String get entrySaveFailedMessage =>
      'Dein Eintrag konnte nicht gespeichert werden. Bitte versuche es noch einmal.';

  @override
  String get sessionReadFailedMessage =>
      'Deine angefangene Session konnte nicht geladen werden. Bitte versuche es noch einmal.';

  @override
  String get startOverButton => 'Neu beginnen';

  @override
  String get tryAgainButton => 'Erneut versuchen';

  @override
  String get submitButton => 'Senden';

  @override
  String get longtextHint => 'Schreib einfach drauflos…';

  @override
  String get textListHint => 'Schreib eine Sache auf…';

  @override
  String answerLengthLeft(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'Noch $count Zeichen',
      one: 'Noch $count Zeichen',
    );
    return '$_temp0';
  }

  @override
  String answerLengthOver(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$count Zeichen zu viel. Kürze deine Antwort, um sie zu senden.',
      one: '$count Zeichen zu viel. Kürze deine Antwort, um sie zu senden.',
    );
    return '$_temp0';
  }

  @override
  String get ratingNoAnswer => 'Keine Antwort';

  @override
  String get colorPickLabel => 'Farbe wählen';

  @override
  String get colorSwatchesTab => 'Grundfarben';

  @override
  String get colorWheelTab => 'Farbrad';

  @override
  String get colorCancelButton => 'Abbrechen';

  @override
  String get colorClearButton => 'Entfernen';

  @override
  String get colorSelectButton => 'Auswählen';

  @override
  String get emojiPickLabel => 'Emoji wählen';

  @override
  String get emojiClearLabel => 'Emoji entfernen';

  @override
  String get emojiSearchHint => 'Lächeln, Herz, …';

  @override
  String get emojiNoRecents => 'Noch keine zuletzt genutzten Emoji';
}
