// coverage:ignore-file
// Generated by flutter gen-l10n from the ARB files in l10n (ADR 0020), so
// the tests of the screens that show each string cover it, not this file.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;

import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for German (`de`).
class AppLocalizationsDe extends AppLocalizations {
  AppLocalizationsDe([String locale = 'de']) : super(locale);

  @override
  String get appTitle => 'emotely';

  @override
  String get journalTab => 'Tagebuch';

  @override
  String get moreTab => 'Mehr';

  @override
  String updateRequiredMessage(String minAppVersion) {
    return 'Diese Version von emotely wird nicht mehr unterstützt. Bitte aktualisiere auf $minAppVersion oder neuer, um weiterzumachen.';
  }

  @override
  String get updateButton => 'Aktualisieren';

  @override
  String get tryAgainButton => 'Erneut versuchen';

  @override
  String get configUnreachableMessage =>
      'emotely ist gerade nicht erreichbar. Prüfe deine Verbindung und versuche es erneut.';

  @override
  String get configUnreadableMessage =>
      'emotely antwortet gerade nicht richtig. Bitte versuche es erneut.';
}
