// coverage:ignore-file
// Generated by flutter gen-l10n from the ARB files in l10n (ADR 0020), so
// the tests of the screens that show each string cover it, not this file.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;

import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get appTitle => 'emotely';

  @override
  String get journalTab => 'Journal';

  @override
  String get moreTab => 'More';

  @override
  String updateRequiredMessage(String minAppVersion) {
    return 'This version of emotely is no longer supported. Please update to $minAppVersion or newer to continue.';
  }

  @override
  String get updateButton => 'Update';

  @override
  String get tryAgainButton => 'Try again';

  @override
  String get configUnreachableMessage =>
      'Could not reach emotely. Check your connection and try again.';

  @override
  String get configUnreadableMessage =>
      'emotely is not answering correctly right now. Please try again.';
}
