// coverage:ignore-file
// Generated by flutter gen-l10n from the ARB files in l10n (ADR 0020), so
// the tests of the screens that show each string cover it, not this file.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;

import 'journal_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class JournalLocalizationsEn extends JournalLocalizations {
  JournalLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String greeting(String partOfDay) {
    String _temp0 = intl.Intl.selectLogic(partOfDay, {
      'morning': 'Good morning',
      'afternoon': 'Good afternoon',
      'other': 'Good evening',
    });
    return '$_temp0';
  }

  @override
  String greetingByName(String partOfDay, String name) {
    String _temp0 = intl.Intl.selectLogic(partOfDay, {
      'morning': 'Good morning, $name',
      'afternoon': 'Good afternoon, $name',
      'other': 'Good evening, $name',
    });
    return '$_temp0';
  }

  @override
  String get startSessionButton => 'Start a session';

  @override
  String get unfinishedSessionMessage => 'You have an unfinished session.';

  @override
  String get continueSessionButton => 'Continue';

  @override
  String get discardSessionButton => 'Discard it';

  @override
  String get emptyJournalMessage =>
      'No entries yet. Your first session writes the first one.';

  @override
  String get journalFailureMessage => 'Could not load your journal.';

  @override
  String get journalRetryButton => 'Try again';

  @override
  String get entryScreenTitle => 'Entry';

  @override
  String get entryFailureMessage => 'Could not load this entry.';

  @override
  String get entryRetryButton => 'Try again';
}
