// coverage:ignore-file
// Generated by flutter gen-l10n from the ARB files in l10n (ADR 0020), so
// the tests of the screens that show each string cover it, not this file.
import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:intl/intl.dart' as intl;

import 'journal_localizations_de.dart';
import 'journal_localizations_en.dart';

// ignore_for_file: type=lint

/// Callers can lookup localized strings with an instance of JournalLocalizations
/// returned by `JournalLocalizations.of(context)`.
///
/// Applications need to include `JournalLocalizations.delegate()` in their app's
/// `localizationDelegates` list, and the locales they support in the app's
/// `supportedLocales` list. For example:
///
/// ```dart
/// import 'l10n/journal_localizations.dart';
///
/// return MaterialApp(
///   localizationsDelegates: JournalLocalizations.localizationsDelegates,
///   supportedLocales: JournalLocalizations.supportedLocales,
///   home: MyApplicationHome(),
/// );
/// ```
///
/// ## Update pubspec.yaml
///
/// Please make sure to update your pubspec.yaml to include the following
/// packages:
///
/// ```yaml
/// dependencies:
///   # Internationalization support.
///   flutter_localizations:
///     sdk: flutter
///   intl: any # Use the pinned version from flutter_localizations
///
///   # Rest of dependencies
/// ```
///
/// ## iOS Applications
///
/// iOS applications define key application metadata, including supported
/// locales, in an Info.plist file that is built into the application bundle.
/// To configure the locales supported by your app, you’ll need to edit this
/// file.
///
/// First, open your project’s ios/Runner.xcworkspace Xcode workspace file.
/// Then, in the Project Navigator, open the Info.plist file under the Runner
/// project’s Runner folder.
///
/// Next, select the Information Property List item, select Add Item from the
/// Editor menu, then select Localizations from the pop-up menu.
///
/// Select and expand the newly-created Localizations item then, for each
/// locale your application supports, add a new item and select the locale
/// you wish to add from the pop-up menu in the Value field. This list should
/// be consistent with the languages listed in the JournalLocalizations.supportedLocales
/// property.
abstract class JournalLocalizations {
  JournalLocalizations(String locale)
    : localeName = intl.Intl.canonicalizedLocale(locale.toString());

  final String localeName;

  static JournalLocalizations of(BuildContext context) {
    return Localizations.of<JournalLocalizations>(
      context,
      JournalLocalizations,
    )!;
  }

  static const LocalizationsDelegate<JournalLocalizations> delegate =
      _JournalLocalizationsDelegate();

  /// A list of this localizations delegate along with the default localizations
  /// delegates.
  ///
  /// Returns a list of localizations delegates containing this delegate along with
  /// GlobalMaterialLocalizations.delegate, GlobalCupertinoLocalizations.delegate,
  /// and GlobalWidgetsLocalizations.delegate.
  ///
  /// Additional delegates can be added by appending to this list in
  /// MaterialApp. This list does not have to be used at all if a custom list
  /// of delegates is preferred or required.
  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates =
      <LocalizationsDelegate<dynamic>>[
        delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ];

  /// A list of this localizations delegate's supported locales.
  static const List<Locale> supportedLocales = <Locale>[
    Locale('en'),
    Locale('de'),
  ];

  /// Journal home, the large heading at the top: greets the user by the time of day on their phone, when their profile holds no name. partOfDay is morning (5:00 to 11:59), afternoon (12:00 to 17:59) or, in every other case, evening, which includes late at night.
  ///
  /// In en, this message translates to:
  /// **'{partOfDay, select, morning{Good morning} afternoon{Good afternoon} other{Good evening}}'**
  String greeting(String partOfDay);

  /// Journal home, the large heading at the top: greets the user by the time of day on their phone and by the name in their profile. partOfDay is morning (5:00 to 11:59), afternoon (12:00 to 17:59) or, in every other case, evening, which includes late at night.
  ///
  /// In en, this message translates to:
  /// **'{partOfDay, select, morning{Good morning, {name}} afternoon{Good afternoon, {name}} other{Good evening, {name}}}'**
  String greetingByName(String partOfDay, String name);

  /// Journal home, the main button: starts a new reflection session, in which emotely asks a few questions and writes a journal entry from the answers.
  ///
  /// In en, this message translates to:
  /// **'Start a session'**
  String get startSessionButton;

  /// Journal home, above the buttons that continue or discard it: the user left a reflection session before it wrote its entry.
  ///
  /// In en, this message translates to:
  /// **'You have an unfinished session.'**
  String get unfinishedSessionMessage;

  /// Journal home, the main button under the unfinished-session notice: picks the unfinished session up where the user left it.
  ///
  /// In en, this message translates to:
  /// **'Continue'**
  String get continueSessionButton;

  /// Journal home, the secondary button under the unfinished-session notice: throws the unfinished session away so the next one starts fresh.
  ///
  /// In en, this message translates to:
  /// **'Discard it'**
  String get discardSessionButton;

  /// Journal home, in place of the list of entries while there are none: explains that entries come from sessions.
  ///
  /// In en, this message translates to:
  /// **'No entries yet. Your first session writes the first one.'**
  String get emptyJournalMessage;

  /// Journal home, shown instead of the journal when its entries or the unfinished session could not be read or changed. Nothing the user did wrong.
  ///
  /// In en, this message translates to:
  /// **'Could not load your journal.'**
  String get journalFailureMessage;

  /// Journal home, under the failure message: reads the journal again.
  ///
  /// In en, this message translates to:
  /// **'Try again'**
  String get journalRetryButton;

  /// Entry screen, the app bar title while the entry is being read or could not be read. Once it is read, the entry's date stands there instead.
  ///
  /// In en, this message translates to:
  /// **'Entry'**
  String get entryScreenTitle;

  /// Entry screen, shown instead of the entry when it could not be read, or the journal no longer holds it.
  ///
  /// In en, this message translates to:
  /// **'Could not load this entry.'**
  String get entryFailureMessage;

  /// Entry screen, under the failure message: reads the entry again.
  ///
  /// In en, this message translates to:
  /// **'Try again'**
  String get entryRetryButton;
}

class _JournalLocalizationsDelegate
    extends LocalizationsDelegate<JournalLocalizations> {
  const _JournalLocalizationsDelegate();

  @override
  Future<JournalLocalizations> load(Locale locale) {
    return SynchronousFuture<JournalLocalizations>(
      lookupJournalLocalizations(locale),
    );
  }

  @override
  bool isSupported(Locale locale) =>
      <String>['de', 'en'].contains(locale.languageCode);

  @override
  bool shouldReload(_JournalLocalizationsDelegate old) => false;
}

JournalLocalizations lookupJournalLocalizations(Locale locale) {
  // Lookup logic when only language code is specified.
  switch (locale.languageCode) {
    case 'de':
      return JournalLocalizationsDe();
    case 'en':
      return JournalLocalizationsEn();
  }

  throw FlutterError(
    'JournalLocalizations.delegate failed to load unsupported locale "$locale". This is likely '
    'an issue with the localizations generation tool. Please file an issue '
    'on GitHub with a reproducible sample app and the gen-l10n configuration '
    'that was used.',
  );
}
