// coverage:ignore-file
// Generated by flutter gen-l10n from the ARB files in l10n (ADR 0020), so
// the tests of the screens that show each string cover it, not this file.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;

import 'journal_localizations.dart';

// ignore_for_file: type=lint

/// The translations for German (`de`).
class JournalLocalizationsDe extends JournalLocalizations {
  JournalLocalizationsDe([String locale = 'de']) : super(locale);

  @override
  String greeting(String partOfDay) {
    String _temp0 = intl.Intl.selectLogic(partOfDay, {
      'morning': 'Guten Morgen',
      'afternoon': 'Guten Tag',
      'other': 'Guten Abend',
    });
    return '$_temp0';
  }

  @override
  String greetingByName(String partOfDay, String name) {
    String _temp0 = intl.Intl.selectLogic(partOfDay, {
      'morning': 'Guten Morgen, $name',
      'afternoon': 'Guten Tag, $name',
      'other': 'Guten Abend, $name',
    });
    return '$_temp0';
  }

  @override
  String get startSessionButton => 'Session starten';

  @override
  String get unfinishedSessionMessage => 'Du hast noch eine offene Session.';

  @override
  String get continueSessionButton => 'Fortsetzen';

  @override
  String get discardSessionButton => 'Verwerfen';

  @override
  String get emptyJournalMessage =>
      'Noch keine Einträge. Deine erste Session schreibt den ersten.';

  @override
  String get journalFailureMessage =>
      'Dein Tagebuch konnte nicht geladen werden.';

  @override
  String get journalRetryButton => 'Erneut versuchen';

  @override
  String get entryScreenTitle => 'Eintrag';

  @override
  String get entryFailureMessage =>
      'Dieser Eintrag konnte nicht geladen werden.';

  @override
  String get entryRetryButton => 'Erneut versuchen';
}
