// coverage:ignore-file
// Generated by flutter gen-l10n from the ARB files in l10n (ADR 0020), so
// the tests of the screens that show each string cover it, not this file.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;

import 'design_system_localizations.dart';

// ignore_for_file: type=lint

/// The translations for German (`de`).
class DesignSystemLocalizationsDe extends DesignSystemLocalizations {
  DesignSystemLocalizationsDe([String locale = 'de']) : super(locale);

  @override
  String get entryViewTitle => 'Dein Eintrag';
}
