// coverage:ignore-file
// Generated by flutter gen-l10n from the ARB files in l10n (ADR 0020), so
// the tests of the screens that show each string cover it, not this file.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;

import 'onboarding_localizations.dart';

// ignore_for_file: type=lint

/// The translations for German (`de`).
class OnboardingLocalizationsDe extends OnboardingLocalizations {
  OnboardingLocalizationsDe([String locale = 'de']) : super(locale);

  @override
  String get welcomeTitle => 'Willkommen bei emotely';

  @override
  String get welcomeBody =>
      'Ein paar begleitete Minuten am Tag, um wahrzunehmen, wie du dich fühlst – und warum.';

  @override
  String get getStartedButton => 'Los geht’s';

  @override
  String get haveAccountButton => 'Ich habe schon ein Konto';

  @override
  String get valueTitle => 'Das bringen dir ein paar Minuten';

  @override
  String get guidedPromiseTitle => 'Begleitet, eine Frage nach der anderen';

  @override
  String get guidedPromiseBody =>
      'Wähl eine Fragenreihe. emotely fragt, hört zu und hakt nach – kein leeres Blatt.';

  @override
  String get answerPromiseTitle => 'Antworte, wie du magst';

  @override
  String get answerPromiseBody =>
      'Worte, Emojis, Farben oder eine schnelle Bewertung – was gerade passt.';

  @override
  String get journalPromiseTitle => 'Ein Tagebuch, das sich selbst schreibt';

  @override
  String get journalPromiseBody =>
      'Aus jeder Session wird ein Eintrag zum Nachlesen – und du siehst, was immer wiederkehrt.';

  @override
  String get continueButton => 'Weiter';

  @override
  String get backTooltip => 'Zurück';

  @override
  String stepProgress(int step, int count) {
    return 'Schritt $step von $count';
  }

  @override
  String get nameTitle => 'Bevor wir anfangen – wie soll ich dich nennen?';

  @override
  String get nameBody => 'Ein Vorname oder ein Spitzname ist perfekt.';

  @override
  String get nameFieldLabel => 'Dein Name';

  @override
  String get nameFieldHint => 'Vorname oder Spitzname';

  @override
  String get nameUse =>
      'Nur, um dich zu begrüßen – in der App und in deinen Sessions. Du kannst ihn jederzeit in deinem Profil ändern.';

  @override
  String nameTooLongError(int max) {
    return 'Das ist mir ein bisschen zu lang – höchstens $max Zeichen.';
  }

  @override
  String get nameInvisibleCharacterError =>
      'Bitte lass Tabs und andere unsichtbare Zeichen weg.';

  @override
  String get skipNameButton => 'Erst mal überspringen';

  @override
  String helloTitle(String name) {
    return 'Schön, dich kennenzulernen, $name.';
  }

  @override
  String get helloBody =>
      'Deine erste Reflexion dauert etwa fünf Minuten. Ich frage, du antwortest – mit Worten, Emojis oder Farben.';

  @override
  String get skippedTitle => 'Gut, bleib geheimnisvoll.';

  @override
  String skippedBody(String placeholder) {
    return 'Ich nenne dich erst mal $placeholder. Wenn du mir deinen echten Namen verraten magst: Das geht in deinem Profil.';
  }

  @override
  String get tellYouButton => 'Ich verrate ihn dir doch';

  @override
  String get startReflectionButton => 'Meine erste Reflexion starten';

  @override
  String get saveFailedMessage =>
      'Ich konnte deinen Namen gerade nicht speichern. Prüfe deine Verbindung und versuche es erneut.';

  @override
  String get retryButton => 'Erneut versuchen';

  @override
  String get placeholderNames =>
      'Kiesel, Krümel, Keks, Spatz, Klee, Nudel, Knopf, Murmel, Hummel, Wuschel, Zimt, Flocke';
}
