// coverage:ignore-file
// Generated by flutter gen-l10n from the ARB files in l10n (ADR 0020), so
// the tests of the screens that show each string cover it, not this file.
import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:intl/intl.dart' as intl;

import 'onboarding_localizations_de.dart';
import 'onboarding_localizations_en.dart';

// ignore_for_file: type=lint

/// Callers can lookup localized strings with an instance of OnboardingLocalizations
/// returned by `OnboardingLocalizations.of(context)`.
///
/// Applications need to include `OnboardingLocalizations.delegate()` in their app's
/// `localizationDelegates` list, and the locales they support in the app's
/// `supportedLocales` list. For example:
///
/// ```dart
/// import 'l10n/onboarding_localizations.dart';
///
/// return MaterialApp(
///   localizationsDelegates: OnboardingLocalizations.localizationsDelegates,
///   supportedLocales: OnboardingLocalizations.supportedLocales,
///   home: MyApplicationHome(),
/// );
/// ```
///
/// ## Update pubspec.yaml
///
/// Please make sure to update your pubspec.yaml to include the following
/// packages:
///
/// ```yaml
/// dependencies:
///   # Internationalization support.
///   flutter_localizations:
///     sdk: flutter
///   intl: any # Use the pinned version from flutter_localizations
///
///   # Rest of dependencies
/// ```
///
/// ## iOS Applications
///
/// iOS applications define key application metadata, including supported
/// locales, in an Info.plist file that is built into the application bundle.
/// To configure the locales supported by your app, you’ll need to edit this
/// file.
///
/// First, open your project’s ios/Runner.xcworkspace Xcode workspace file.
/// Then, in the Project Navigator, open the Info.plist file under the Runner
/// project’s Runner folder.
///
/// Next, select the Information Property List item, select Add Item from the
/// Editor menu, then select Localizations from the pop-up menu.
///
/// Select and expand the newly-created Localizations item then, for each
/// locale your application supports, add a new item and select the locale
/// you wish to add from the pop-up menu in the Value field. This list should
/// be consistent with the languages listed in the OnboardingLocalizations.supportedLocales
/// property.
abstract class OnboardingLocalizations {
  OnboardingLocalizations(String locale)
    : localeName = intl.Intl.canonicalizedLocale(locale.toString());

  final String localeName;

  static OnboardingLocalizations of(BuildContext context) {
    return Localizations.of<OnboardingLocalizations>(
      context,
      OnboardingLocalizations,
    )!;
  }

  static const LocalizationsDelegate<OnboardingLocalizations> delegate =
      _OnboardingLocalizationsDelegate();

  /// A list of this localizations delegate along with the default localizations
  /// delegates.
  ///
  /// Returns a list of localizations delegates containing this delegate along with
  /// GlobalMaterialLocalizations.delegate, GlobalCupertinoLocalizations.delegate,
  /// and GlobalWidgetsLocalizations.delegate.
  ///
  /// Additional delegates can be added by appending to this list in
  /// MaterialApp. This list does not have to be used at all if a custom list
  /// of delegates is preferred or required.
  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates =
      <LocalizationsDelegate<dynamic>>[
        delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ];

  /// A list of this localizations delegate's supported locales.
  static const List<Locale> supportedLocales = <Locale>[
    Locale('en'),
    Locale('de'),
  ];

  /// Onboarding, Welcome step (the first screen a new user sees): the heading. emotely is the product name, always lower case, never translated.
  ///
  /// In en, this message translates to:
  /// **'Welcome to emotely'**
  String get welcomeTitle;

  /// Onboarding, Welcome step: the one line under the heading saying what emotely is for, a reflective journal that guides the user.
  ///
  /// In en, this message translates to:
  /// **'A few guided minutes a day to notice how you feel – and why.'**
  String get welcomeBody;

  /// Onboarding, Welcome step: the main button that starts onboarding for someone new.
  ///
  /// In en, this message translates to:
  /// **'Get started'**
  String get getStartedButton;

  /// Onboarding, Welcome step: the quieter button under Get started, for someone who already has an account; it skips onboarding and opens sign-in.
  ///
  /// In en, this message translates to:
  /// **'I have an account'**
  String get haveAccountButton;

  /// Onboarding, second step: the heading over three promises of what a few minutes a day with emotely gives the user.
  ///
  /// In en, this message translates to:
  /// **'Here is what a few minutes gets you'**
  String get valueTitle;

  /// Onboarding, second step, first of three promises (next to a speech bubble icon): the companion asks one question at a time.
  ///
  /// In en, this message translates to:
  /// **'Guided, one question at a time'**
  String get guidedPromiseTitle;

  /// Onboarding, second step, the line under the first promise. "No blank page": unlike a paper diary, the user never faces an empty page.
  ///
  /// In en, this message translates to:
  /// **'Pick a set of questions. emotely asks, listens and follows up – no blank page.'**
  String get guidedPromiseBody;

  /// Onboarding, second step, second of three promises (next to a palette icon): the user can answer in many forms.
  ///
  /// In en, this message translates to:
  /// **'Answer your way'**
  String get answerPromiseTitle;

  /// Onboarding, second step, the line under the second promise: the kinds of answer a session accepts.
  ///
  /// In en, this message translates to:
  /// **'Words, emojis, colors or a quick rating – whatever fits the moment.'**
  String get answerPromiseBody;

  /// Onboarding, second step, third of three promises (next to a book icon): each session is turned into a journal entry for the user.
  ///
  /// In en, this message translates to:
  /// **'A journal that writes itself'**
  String get journalPromiseTitle;

  /// Onboarding, second step, the line under the third promise: rereading entries shows the user their recurring themes.
  ///
  /// In en, this message translates to:
  /// **'Every session ends in an entry you can reread – and spot what keeps coming back.'**
  String get journalPromiseBody;

  /// Onboarding, the main button of the second step and of the name step: goes on to the next step.
  ///
  /// In en, this message translates to:
  /// **'Continue'**
  String get continueButton;

  /// Onboarding, every step after the first: tooltip and screen-reader label of the arrow at the top left that goes back one step.
  ///
  /// In en, this message translates to:
  /// **'Back'**
  String get backTooltip;

  /// Onboarding, top of each step: what a screen reader says for the row of dots that shows how far the user is.
  ///
  /// In en, this message translates to:
  /// **'Step {step} of {count}'**
  String stepProgress(int step, int count);

  /// Onboarding, name step: the heading. The companion speaks as "I" and asks, informally, what name to greet the user by.
  ///
  /// In en, this message translates to:
  /// **'Before we start – what should I call you?'**
  String get nameTitle;

  /// Onboarding, name step: the line under the heading, reassuring the user that any name will do.
  ///
  /// In en, this message translates to:
  /// **'A first name or a nickname is perfect.'**
  String get nameBody;

  /// Onboarding, name step: the label of the one text field, where the user types the name to be called by.
  ///
  /// In en, this message translates to:
  /// **'Your name'**
  String get nameFieldLabel;

  /// Onboarding, name step: the grey hint inside the empty name field.
  ///
  /// In en, this message translates to:
  /// **'First name or nickname'**
  String get nameFieldHint;

  /// Onboarding, name step: the small print under the name field, next to a lock icon, saying what the name is used for.
  ///
  /// In en, this message translates to:
  /// **'Only used to greet you – in the app and in your sessions. Change it any time in your profile.'**
  String get nameUse;

  /// Onboarding, name step: the error under the name field when the typed name is longer than allowed. Spoken by the companion, gently.
  ///
  /// In en, this message translates to:
  /// **'That is a little long for me – {max} characters at most.'**
  String nameTooLongError(int max);

  /// Onboarding, name step: the error under the name field when the typed name holds a tab, a line break or another invisible character that rearranges text.
  ///
  /// In en, this message translates to:
  /// **'Please leave out tabs and other invisible characters.'**
  String get nameInvisibleCharacterError;

  /// Onboarding, name step: the quieter button under Continue that goes on without a name; emotely then picks a playful placeholder name for the user.
  ///
  /// In en, this message translates to:
  /// **'Skip for now'**
  String get skipNameButton;

  /// Onboarding, greeting step after the user typed a name: the heading, greeting them by it.
  ///
  /// In en, this message translates to:
  /// **'Nice to meet you, {name}.'**
  String helloTitle(String name);

  /// Onboarding, greeting step: the line under the heading, saying what the first session is like. The companion speaks as "I".
  ///
  /// In en, this message translates to:
  /// **'Your first reflection takes about five minutes. I ask, you answer – in words, emojis or colors.'**
  String get helloBody;

  /// Onboarding, greeting step after the user skipped the name: a playful, good-natured heading accepting that they did not say.
  ///
  /// In en, this message translates to:
  /// **'Fine, stay mysterious.'**
  String get skippedTitle;

  /// Onboarding, greeting step after a skip: announces the name emotely picked (one of placeholderNames) and says the real name can be given later in the profile.
  ///
  /// In en, this message translates to:
  /// **'I’ll call you {placeholder} for now. When you’re ready to tell me your real name, it’s in your profile.'**
  String skippedBody(String placeholder);

  /// Onboarding, greeting step after a skip: the quieter button that takes the user back to the name field after all.
  ///
  /// In en, this message translates to:
  /// **'Actually, I’ll tell you'**
  String get tellYouButton;

  /// Onboarding, greeting step: the main button, the last step before sign-up, which leads on to the user's first session.
  ///
  /// In en, this message translates to:
  /// **'Start my first reflection'**
  String get startReflectionButton;

  /// Onboarding, right after sign-up: the name could not be saved to the new account. Shown above a Try again button.
  ///
  /// In en, this message translates to:
  /// **'I could not save your name just now. Check your connection and try again.'**
  String get saveFailedMessage;

  /// Onboarding, right after sign-up: the button under the failed-save message that tries saving the name again.
  ///
  /// In en, this message translates to:
  /// **'Try again'**
  String get retryButton;

  /// Onboarding: the placeholder names emotely picks one of, at random, when the user skips the name step. The pick becomes the user's name: shown in the greeting and the profile, and given to the companion, and it stays as picked even if the phone's language changes later. Separated by commas. Do not translate word for word: give equally playful, gender-neutral names that are plainly nobody's real name, each at most 40 characters. The number of names may differ.
  ///
  /// In en, this message translates to:
  /// **'Pebble, Pip, Maple, Biscuit, Sparrow, Clover, Noodle, Sunny, Juniper, Button, Toffee, Wren'**
  String get placeholderNames;
}

class _OnboardingLocalizationsDelegate
    extends LocalizationsDelegate<OnboardingLocalizations> {
  const _OnboardingLocalizationsDelegate();

  @override
  Future<OnboardingLocalizations> load(Locale locale) {
    return SynchronousFuture<OnboardingLocalizations>(
      lookupOnboardingLocalizations(locale),
    );
  }

  @override
  bool isSupported(Locale locale) =>
      <String>['de', 'en'].contains(locale.languageCode);

  @override
  bool shouldReload(_OnboardingLocalizationsDelegate old) => false;
}

OnboardingLocalizations lookupOnboardingLocalizations(Locale locale) {
  // Lookup logic when only language code is specified.
  switch (locale.languageCode) {
    case 'de':
      return OnboardingLocalizationsDe();
    case 'en':
      return OnboardingLocalizationsEn();
  }

  throw FlutterError(
    'OnboardingLocalizations.delegate failed to load unsupported locale "$locale". This is likely '
    'an issue with the localizations generation tool. Please file an issue '
    'on GitHub with a reproducible sample app and the gen-l10n configuration '
    'that was used.',
  );
}
