// coverage:ignore-file
// Generated by flutter gen-l10n from the ARB files in l10n (ADR 0020), so
// the tests of the screens that show each string cover it, not this file.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;

import 'onboarding_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class OnboardingLocalizationsEn extends OnboardingLocalizations {
  OnboardingLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get welcomeTitle => 'Welcome to emotely';

  @override
  String get welcomeBody =>
      'A few guided minutes a day to notice how you feel – and why.';

  @override
  String get getStartedButton => 'Get started';

  @override
  String get haveAccountButton => 'I have an account';

  @override
  String get valueTitle => 'Here is what a few minutes gets you';

  @override
  String get guidedPromiseTitle => 'Guided, one question at a time';

  @override
  String get guidedPromiseBody =>
      'Pick a set of questions. emotely asks, listens and follows up – no blank page.';

  @override
  String get answerPromiseTitle => 'Answer your way';

  @override
  String get answerPromiseBody =>
      'Words, emojis, colours or a quick rating – whatever fits the moment.';

  @override
  String get journalPromiseTitle => 'A journal that writes itself';

  @override
  String get journalPromiseBody =>
      'Every session ends in an entry you can reread – and spot what keeps coming back.';

  @override
  String get continueButton => 'Continue';

  @override
  String get backTooltip => 'Back';

  @override
  String stepProgress(int step, int count) {
    return 'Step $step of $count';
  }

  @override
  String get nameTitle => 'Before we start – what should I call you?';

  @override
  String get nameBody => 'A first name or a nickname is perfect.';

  @override
  String get nameFieldLabel => 'Your name';

  @override
  String get nameFieldHint => 'First name or nickname';

  @override
  String get nameUse =>
      'Only used to greet you – in the app and in your sessions. Change it any time in your profile.';

  @override
  String nameTooLongError(int max) {
    return 'That is a little long for me – $max characters at most.';
  }

  @override
  String get nameInvisibleCharacterError =>
      'Please leave out tabs and other invisible characters.';

  @override
  String get skipNameButton => 'Skip for now';

  @override
  String helloTitle(String name) {
    return 'Nice to meet you, $name.';
  }

  @override
  String get helloBody =>
      'Your first reflection takes about five minutes. I ask, you answer – in words, emojis or colours.';

  @override
  String get skippedTitle => 'Fine, stay mysterious.';

  @override
  String skippedBody(String placeholder) {
    return 'I’ll call you $placeholder for now. When you’re ready to tell me your real name, it’s in your profile.';
  }

  @override
  String get tellYouButton => 'Actually, I’ll tell you';

  @override
  String get startReflectionButton => 'Start my first reflection';

  @override
  String get saveFailedMessage =>
      'I could not save your name just now. Check your connection and try again.';

  @override
  String get retryButton => 'Try again';

  @override
  String get placeholderNames =>
      'Pebble, Pip, Maple, Biscuit, Sparrow, Clover, Noodle, Sunny, Juniper, Button, Toffee, Wren';
}
