// coverage:ignore-file
// Generated by flutter gen-l10n from the ARB files in l10n (ADR 0020), so
// the tests of the screens that show each string cover it, not this file.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;

import 'account_localizations.dart';

// ignore_for_file: type=lint

/// The translations for German (`de`).
class AccountLocalizationsDe extends AccountLocalizations {
  AccountLocalizationsDe([String locale = 'de']) : super(locale);

  @override
  String get consentTitle => 'Bevor emotely sendet, was du schreibst';

  @override
  String get consentSendingLead =>
      'Deine Antworten werden an ein KI-Modell gesendet.';

  @override
  String get consentSendingBody =>
      'Jede Antwort geht an unseren Server und von dort über das Vercel AI Gateway an einen Anbieter von Sprachmodellen, zusammen mit dem Namen, den du gewählt hast oder den emotely für dich ausgesucht hat, und der Sprache, auf die die App eingestellt ist, damit emotely dir die nächste Frage in deiner Sprache stellen, dich mit deinem Namen ansprechen und deinen Eintrag schreiben kann. Der Anbieter kann außerhalb der EU sitzen; in diesem Fall stützt sich die Übermittlung auf die Standardvertragsklauseln der EU.';

  @override
  String get consentRetentionLead =>
      'Nie für Training genutzt, nie aufbewahrt.';

  @override
  String get consentRetentionBody =>
      'Jede Anfrage geht nur an Anbieter, denen vertraglich untersagt ist, mit dem, was du schreibst, zu trainieren und es nach ihrer Antwort aufzubewahren. Deine Einträge selbst werden in Frankfurt gespeichert und nirgendwo sonst.';

  @override
  String get consentWithdrawalLead => 'Sensibel – und jederzeit widerrufbar.';

  @override
  String get consentWithdrawalBody =>
      'Ein Tagebuch kann zeigen, wie du dich fühlst, wie du schläfst oder wie es um deine Gesundheit steht, deshalb fragen wir vorher. Du kannst jederzeit im Tab „Mehr“ widerrufen; was ein Anbieter bereits beantwortet hat, lässt sich nicht zurückholen.';

  @override
  String get consentCheckboxLabel =>
      'Ich willige ein, dass meine Tagebucheinträge wie oben beschrieben an einen Anbieter von Sprachmodellen gesendet werden.';

  @override
  String get consentAgreeButton => 'Tagebuch beginnen';

  @override
  String get consentDeclineButton => 'Nicht jetzt';

  @override
  String get consentAgreeBlockedHint =>
      'Setze oben das Häkchen, um fortzufahren';

  @override
  String get consentDeclinedMessage =>
      'Kein Problem. Es wurde nichts gesendet. Deine bisherigen Einträge kannst du weiter lesen, und eine Session kannst du starten, wann immer du dich dafür entscheidest.';

  @override
  String get consentReadNoticeLink =>
      'Die vollständige Datenschutzerklärung lesen';

  @override
  String get consentFailureMessage =>
      'Deine Einwilligung konnte nicht gespeichert werden. Prüfe deine Verbindung und versuche es erneut.';

  @override
  String get consentWithdrawFailureMessage =>
      'Dein Widerruf konnte nicht gespeichert werden. Prüfe deine Verbindung und versuche es erneut.';

  @override
  String get consentUnknownMessage =>
      'Es ließ sich nicht prüfen, ob du dem schon zugestimmt hast. Es wurde nichts gesendet. Prüfe deine Verbindung und versuche es erneut.';

  @override
  String get consentRetryButton => 'Erneut versuchen';

  @override
  String get consentBackButton => 'Zurück';

  @override
  String get usageAnalyticsTitle => 'Darf ich zählen, wie du die App nutzt?';

  @override
  String get usageAnalyticsBody =>
      'So sehe ich, welche Bildschirme helfen und wo Leute hängen bleiben, und kann besser werden. Was du schreibst, fließt nie ein.';

  @override
  String get usageAnalyticsCounted =>
      'Antippen, Bildschirme und Absturzberichte, gespeichert bei PostHog in der EU';

  @override
  String get usageAnalyticsNever =>
      'Nie deine Antworten, Einträge oder dein Name';

  @override
  String get usageAnalyticsDenyButton => 'Nicht erlauben';

  @override
  String get usageAnalyticsAllowButton => 'Erlauben';

  @override
  String get usageAnalyticsChangeHint =>
      'Du kannst das jederzeit unter Mehr › Datenschutzeinstellungen ändern.';

  @override
  String get usageAnalyticsNoticeLink => 'Datenschutzerklärung';

  @override
  String get moreTitle => 'Mehr';

  @override
  String get morePrivacySection => 'Datenschutz';

  @override
  String get moreAboutSection => 'Info';

  @override
  String get moreAccountSection => 'Konto';

  @override
  String get morePrivacySettingsRow => 'Datenschutzeinstellungen';

  @override
  String get moreJournalAllowedStatus => 'Tagebuch: erlaubt';

  @override
  String get moreJournalOffStatus => 'Tagebuch: aus';

  @override
  String get moreUsageAnalyticsOnStatus => 'Nutzungsanalyse: an';

  @override
  String get moreUsageAnalyticsOffStatus => 'Nutzungsanalyse: aus';

  @override
  String get morePrivacyNoticeRow => 'Datenschutzerklärung';

  @override
  String get moreFeedbackRow => 'Feedback senden';

  @override
  String get moreFeedbackExplanation =>
      'Öffnet deine Mail-App. Enthält deine App-Version und dein Gerät, nichts aus deinem Tagebuch.';

  @override
  String get moreImprintRow => 'Impressum';

  @override
  String get moreDeleteAccountRow => 'Konto löschen';

  @override
  String get moreDeleteAccountExplanation =>
      'Entfernt dein Konto und alle Einträge.';

  @override
  String get profileCardTitle => 'Dein Profil';

  @override
  String get profileCardAddName => 'Namen hinzufügen';

  @override
  String get privacySettingsTitle => 'Datenschutzeinstellungen';

  @override
  String get privacyJournalLabel => 'Tagebuch-Sessions';

  @override
  String get privacyJournalExplanation =>
      'Deine Antworten gehen an ein Sprachmodell, das jede Session begleitet. Nie für Training genutzt, nie vom Anbieter aufbewahrt.';

  @override
  String get privacyJournalOnNote =>
      'Schaltest du das aus, starten keine neuen Sessions mehr; deine Einträge bleiben.';

  @override
  String get privacyJournalOffNote =>
      'Aus: Es kann keine neue Session starten. Beim Einschalten siehst du zuerst, wozu du einwilligst.';

  @override
  String privacyJournalGiven(DateTime date) {
    final intl.DateFormat dateDateFormat = intl.DateFormat.yMMMd(localeName);
    final String dateString = dateDateFormat.format(date);

    return 'Erteilt am $dateString.';
  }

  @override
  String get privacyJournalRetryButton => 'Erneut prüfen';

  @override
  String get privacyConfirmTitle => 'Tagebuch-Sessions ausschalten?';

  @override
  String get privacyConfirmMessage =>
      'Neue Sessions starten nicht mehr; deine Einträge bleiben.';

  @override
  String get privacyConfirmButton => 'Ausschalten';

  @override
  String get privacyCancelButton => 'Abbrechen';

  @override
  String get privacyUsageAnalyticsLabel => 'Nutzungsanalyse';

  @override
  String get privacyUsageAnalyticsExplanation =>
      'Antippen, Bildschirme und Absturzberichte, damit ich sehe, was hilft und wo Leute hängen bleiben. Nie, was du schreibst.';

  @override
  String get privacyUsageAnalyticsNote => 'Gespeichert bei PostHog in der EU.';

  @override
  String get privacyNoticeLink => 'Datenschutzerklärung lesen';

  @override
  String get profileTitle => 'Profil';

  @override
  String get profileNameLabel => 'Name';

  @override
  String get profileNameHint => 'Wie soll ich dich nennen?';

  @override
  String get profileNameHelper => 'So begrüßt dich emotely.';

  @override
  String profilePlaceholderLine(String name) {
    return '$name · ein Name von mir – sag mir deinen';
  }

  @override
  String get profileSavedMessage => 'Gespeichert';

  @override
  String get profileNameEmptyMessage =>
      'Ein Name braucht mindestens ein Zeichen.';

  @override
  String get profileNameRefusedMessage =>
      'Dieser Name enthält ein Zeichen, das ich nicht verwenden kann.';

  @override
  String get profileSaveFailedMessage =>
      'Ich konnte den Namen nicht speichern. Versuch es gleich noch einmal.';

  @override
  String get profileLoadFailedMessage => 'Ich konnte deinen Namen nicht laden.';

  @override
  String get profileRetryButton => 'Erneut versuchen';

  @override
  String get profileSignedInAsLabel => 'Angemeldet als';

  @override
  String get profileSignOutButton => 'Abmelden';

  @override
  String get signInHiddenByApple => 'Von Apple verborgen';

  @override
  String get signInViaEmailCode =>
      'Per E-Mail-Code. Hierhin gehen Anmeldecodes und Mails zu deinem Konto.';

  @override
  String get signInViaGoogle =>
      'Über Google. Hierhin gehen Mails zu deinem Konto.';

  @override
  String get signInViaApple =>
      'Über Apple. Hierhin gehen Mails zu deinem Konto.';

  @override
  String get signInViaAppleRelay =>
      'Von Apple verborgen (privates Relay). Apple leitet Mails zu deinem Konto an dich weiter.';

  @override
  String get signInViaUnknown => 'Hierhin gehen Mails zu deinem Konto.';

  @override
  String get accountTitle => 'Konto';

  @override
  String get accountConsequenceMessage =>
      'Wenn du dein Konto löschst, werden auch alle Tagebucheinträge gelöscht, die du geschrieben hast. Das lässt sich nicht rückgängig machen.';

  @override
  String get accountDeleteButton => 'Konto löschen';

  @override
  String get accountConfirmationMessage =>
      'Dein Konto und alle Einträge löschen?';

  @override
  String get accountCancelButton => 'Abbrechen';

  @override
  String get accountConfirmDeleteButton => 'Löschen';

  @override
  String get accountFailureMessage =>
      'Dein Konto konnte nicht gelöscht werden. Prüfe deine Verbindung und versuche es erneut.';

  @override
  String get accountRetryButton => 'Erneut versuchen';

  @override
  String get accountSignOutButton => 'Abmelden';

  @override
  String get accountConfirmationAppleNote =>
      'Apple fragt dich danach noch einmal, damit emotely sich von deinem Apple Account trennen kann.';

  @override
  String accountDeletedStillLinked(String provider) {
    String _temp0 = intl.Intl.selectLogic(provider, {
      'apple': 'Dein Konto ist gelöscht. emotely steht womöglich noch in deinem Apple Account unter „Mit Apple anmelden“. Dort kannst du es entfernen.',
      'google': 'Dein Konto ist gelöscht. emotely steht womöglich noch unter den verbundenen Apps deines Google-Kontos. Dort kannst du es entfernen.',
      'other': 'Dein Konto ist gelöscht. emotely steht womöglich noch in deinem Apple Account und deinem Google-Konto. Dort kannst du es in den Einstellungen entfernen.',
    });
    return '$_temp0';
  }
}
