// coverage:ignore-file
// Generated by flutter gen-l10n from the ARB files in l10n (ADR 0020), so
// the tests of the screens that show each string cover it, not this file.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;

import 'account_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AccountLocalizationsEn extends AccountLocalizations {
  AccountLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get consentTitle => 'Before emotely sends your writing';

  @override
  String get consentSendingLead => 'Your answers are sent to an AI model.';

  @override
  String get consentSendingBody =>
      'Each answer goes to our server and on to a language model provider through the Vercel AI Gateway, together with the name you chose or emotely picked for you and the language the app is set to, so emotely can ask the next question in your language, address you by name and write your entry. The provider may be outside the EU; where it is, the transfer rests on the EU’s standard contractual clauses.';

  @override
  String get consentRetentionLead => 'Never used for training, never kept.';

  @override
  String get consentRetentionBody =>
      'Every request routes only to providers contractually barred from training on what you write and from keeping it after they answer. Your entries themselves are stored in Frankfurt and nowhere else.';

  @override
  String get consentWithdrawalLead => 'Sensitive, and yours to take back.';

  @override
  String get consentWithdrawalBody =>
      'A journal can say how you feel, how you sleep or how your health is, so we ask first. You can withdraw on the More tab at any time; what a provider has already answered cannot be recalled.';

  @override
  String get consentCheckboxLabel =>
      'I consent to my journal entries being sent to a model provider as described above.';

  @override
  String get consentAgreeButton => 'Start journaling';

  @override
  String get consentDeclineButton => 'Not now';

  @override
  String get consentAgreeBlockedHint => 'Tick the box above to continue';

  @override
  String get consentDeclinedMessage =>
      'No problem. Nothing has been sent. You can still read the entries you already have, and you can start a session whenever you decide to.';

  @override
  String get consentReadNoticeLink => 'Read the full privacy notice';

  @override
  String get consentFailureMessage =>
      'Could not record your consent. Check your connection and try again.';

  @override
  String get consentWithdrawFailureMessage =>
      'Could not withdraw your consent. Check your connection and try again.';

  @override
  String get consentUnknownMessage =>
      'Could not check whether you have already agreed to this. Nothing has been sent. Check your connection and try again.';

  @override
  String get consentRetryButton => 'Try again';

  @override
  String get consentBackButton => 'Back';

  @override
  String get usageAnalyticsTitle => 'May I count how you use the app?';

  @override
  String get usageAnalyticsBody =>
      'It shows which screens help and where people get stuck, so I can get better. What you write never goes into it.';

  @override
  String get usageAnalyticsCounted =>
      'Taps, screens and crash reports, stored with PostHog in the EU';

  @override
  String get usageAnalyticsNever => 'Never your answers, entries or name';

  @override
  String get usageAnalyticsDenyButton => 'Don’t allow';

  @override
  String get usageAnalyticsAllowButton => 'Allow';

  @override
  String get usageAnalyticsChangeHint =>
      'Change it any time under More › Privacy settings.';

  @override
  String get usageAnalyticsNoticeLink => 'Privacy notice';

  @override
  String get moreTitle => 'More';

  @override
  String get morePrivacySection => 'Privacy';

  @override
  String get moreAboutSection => 'About';

  @override
  String get moreAccountSection => 'Account';

  @override
  String get morePrivacySettingsRow => 'Privacy settings';

  @override
  String get moreJournalAllowedStatus => 'Journal: allowed';

  @override
  String get moreJournalOffStatus => 'Journal: off';

  @override
  String get moreUsageAnalyticsOnStatus => 'Usage analytics: on';

  @override
  String get moreUsageAnalyticsOffStatus => 'Usage analytics: off';

  @override
  String get morePrivacyNoticeRow => 'Privacy notice';

  @override
  String get moreFeedbackRow => 'Send feedback';

  @override
  String get moreFeedbackExplanation =>
      'Opens your mail app. Carries your app version and device, nothing from your journal.';

  @override
  String get moreImprintRow => 'Imprint';

  @override
  String get moreDeleteAccountRow => 'Delete account';

  @override
  String get moreDeleteAccountExplanation =>
      'Removes your account and every entry.';

  @override
  String get profileCardTitle => 'Your profile';

  @override
  String get profileCardAddName => 'Add your name';

  @override
  String get privacySettingsTitle => 'Privacy settings';

  @override
  String get privacyJournalLabel => 'Journal sessions';

  @override
  String get privacyJournalExplanation =>
      'Your answers go to a language model to guide each session. Never used for training, never kept by the provider.';

  @override
  String get privacyJournalOnNote =>
      'Turning this off stops new sessions; your entries stay.';

  @override
  String get privacyJournalOffNote =>
      'Off: no new session can start. Turning it on shows you what you agree to first.';

  @override
  String privacyJournalGiven(DateTime date) {
    final intl.DateFormat dateDateFormat = intl.DateFormat.yMMMd(localeName);
    final String dateString = dateDateFormat.format(date);

    return 'Given $dateString.';
  }

  @override
  String get privacyJournalRetryButton => 'Check again';

  @override
  String get privacyConfirmTitle => 'Turn off journal sessions?';

  @override
  String get privacyConfirmMessage => 'New sessions stop; your entries stay.';

  @override
  String get privacyConfirmButton => 'Turn off';

  @override
  String get privacyCancelButton => 'Cancel';

  @override
  String get privacyUsageAnalyticsLabel => 'Usage analytics';

  @override
  String get privacyUsageAnalyticsExplanation =>
      'Taps, screens and crash reports, so I can see what helps and where people get stuck. Never what you write.';

  @override
  String get privacyUsageAnalyticsNote => 'Stored with PostHog in the EU.';

  @override
  String get privacyNoticeLink => 'Read the privacy notice';

  @override
  String get profileTitle => 'Profile';

  @override
  String get profileNameLabel => 'Name';

  @override
  String get profileNameHint => 'What should I call you?';

  @override
  String get profileNameHelper => 'How emotely greets you.';

  @override
  String profilePlaceholderLine(String name) {
    return '$name · a name I picked – tell me yours';
  }

  @override
  String get profileSavedMessage => 'Saved';

  @override
  String get profileNameEmptyMessage => 'A name needs at least one character.';

  @override
  String get profileNameRefusedMessage =>
      'That name has a character I can’t use.';

  @override
  String get profileSaveFailedMessage =>
      'I couldn’t save that name. Try again in a moment.';

  @override
  String get profileLoadFailedMessage => 'I couldn’t load your name.';

  @override
  String get profileRetryButton => 'Try again';

  @override
  String get profileSignedInAsLabel => 'Signed in as';

  @override
  String get profileSignOutButton => 'Sign out';

  @override
  String get signInHiddenByApple => 'Hidden by Apple';

  @override
  String get signInViaEmailCode =>
      'Via email code. This is where sign-in codes and account mail go.';

  @override
  String get signInViaGoogle => 'Via Google. This is where account mail goes.';

  @override
  String get signInViaApple => 'Via Apple. This is where account mail goes.';

  @override
  String get signInViaAppleRelay =>
      'Hidden by Apple (private relay). Apple forwards account mail to you.';

  @override
  String get signInViaUnknown => 'This is where account mail goes.';

  @override
  String get accountTitle => 'Account';

  @override
  String get accountConsequenceMessage =>
      'Deleting your account also deletes every journal entry you wrote. There is no way back.';

  @override
  String get accountDeleteButton => 'Delete account';

  @override
  String get accountConfirmationMessage =>
      'Delete your account and every entry?';

  @override
  String get accountCancelButton => 'Cancel';

  @override
  String get accountConfirmDeleteButton => 'Delete';

  @override
  String get accountFailureMessage =>
      'Could not delete your account. Check your connection and try again.';

  @override
  String get accountRetryButton => 'Try again';

  @override
  String get accountSignOutButton => 'Sign out';

  @override
  String accountDeletedStillLinked(String provider) {
    String _temp0 = intl.Intl.selectLogic(provider, {
      'apple': 'Your account is deleted. emotely may still be listed in your Apple Account under Sign in with Apple. You can remove it there.',
      'google': 'Your account is deleted. emotely may still be listed among your Google Account\'s connected apps. You can remove it there.',
      'other': 'Your account is deleted. emotely may still be listed in your Apple Account and your Google Account. You can remove it in their settings.',
    });
    return '$_temp0';
  }
}
