// coverage:ignore-file
// Generated by flutter gen-l10n from the ARB files in l10n (ADR 0020), so
// the tests of the screens that show each string cover it, not this file.
import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:intl/intl.dart' as intl;

import 'account_localizations_de.dart';
import 'account_localizations_en.dart';

// ignore_for_file: type=lint

/// Callers can lookup localized strings with an instance of AccountLocalizations
/// returned by `AccountLocalizations.of(context)`.
///
/// Applications need to include `AccountLocalizations.delegate()` in their app's
/// `localizationDelegates` list, and the locales they support in the app's
/// `supportedLocales` list. For example:
///
/// ```dart
/// import 'l10n/account_localizations.dart';
///
/// return MaterialApp(
///   localizationsDelegates: AccountLocalizations.localizationsDelegates,
///   supportedLocales: AccountLocalizations.supportedLocales,
///   home: MyApplicationHome(),
/// );
/// ```
///
/// ## Update pubspec.yaml
///
/// Please make sure to update your pubspec.yaml to include the following
/// packages:
///
/// ```yaml
/// dependencies:
///   # Internationalization support.
///   flutter_localizations:
///     sdk: flutter
///   intl: any # Use the pinned version from flutter_localizations
///
///   # Rest of dependencies
/// ```
///
/// ## iOS Applications
///
/// iOS applications define key application metadata, including supported
/// locales, in an Info.plist file that is built into the application bundle.
/// To configure the locales supported by your app, you’ll need to edit this
/// file.
///
/// First, open your project’s ios/Runner.xcworkspace Xcode workspace file.
/// Then, in the Project Navigator, open the Info.plist file under the Runner
/// project’s Runner folder.
///
/// Next, select the Information Property List item, select Add Item from the
/// Editor menu, then select Localizations from the pop-up menu.
///
/// Select and expand the newly-created Localizations item then, for each
/// locale your application supports, add a new item and select the locale
/// you wish to add from the pop-up menu in the Value field. This list should
/// be consistent with the languages listed in the AccountLocalizations.supportedLocales
/// property.
abstract class AccountLocalizations {
  AccountLocalizations(String locale)
    : localeName = intl.Intl.canonicalizedLocale(locale.toString());

  final String localeName;

  static AccountLocalizations of(BuildContext context) {
    return Localizations.of<AccountLocalizations>(
      context,
      AccountLocalizations,
    )!;
  }

  static const LocalizationsDelegate<AccountLocalizations> delegate =
      _AccountLocalizationsDelegate();

  /// A list of this localizations delegate along with the default localizations
  /// delegates.
  ///
  /// Returns a list of localizations delegates containing this delegate along with
  /// GlobalMaterialLocalizations.delegate, GlobalCupertinoLocalizations.delegate,
  /// and GlobalWidgetsLocalizations.delegate.
  ///
  /// Additional delegates can be added by appending to this list in
  /// MaterialApp. This list does not have to be used at all if a custom list
  /// of delegates is preferred or required.
  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates =
      <LocalizationsDelegate<dynamic>>[
        delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ];

  /// A list of this localizations delegate's supported locales.
  static const List<Locale> supportedLocales = <Locale>[
    Locale('en'),
    Locale('de'),
  ];

  /// Consent screen heading, shown before the first journaling session. Part of the versioned wording of the explicit consent under Art. 9 (2) (a) GDPR: changing it (in any language) means bumping consentVersion. Names the moment rather than asking a question, and stays true when the screen is shown again after a wording change or a withdrawal, neither of which is a 'first' session.
  ///
  /// In en, this message translates to:
  /// **'Before emotely sends your writing'**
  String get consentTitle;

  /// Consent screen, first of three points: its bold lead, followed in the same sentence by consentSendingBody. Part of the versioned wording of the explicit consent under Art. 9 (2) (a) GDPR: changing it means bumping consentVersion.
  ///
  /// In en, this message translates to:
  /// **'Your answers are sent to an AI model.'**
  String get consentSendingLead;

  /// Consent screen, first point, after its lead: what is sent, to whom, and the third-country transfer with its safeguard (EDPB 05/2020 para 64 (vi)). Part of the versioned wording of the explicit consent under Art. 9 (2) (a) GDPR: changing it means bumping consentVersion. The recipients must match the privacy notice at getemotely.com/app-privacy: same recipients, same order, same names. 'Vercel AI Gateway' is a product name and stays as is.
  ///
  /// In en, this message translates to:
  /// **'Each answer goes to our server and on to a language model provider through the Vercel AI Gateway, together with the name you chose or emotely picked for you and the language the app is set to, so emotely can ask the next question in your language, address you by name and write your entry. The provider may be outside the EU; where it is, the transfer rests on the EU’s standard contractual clauses.'**
  String get consentSendingBody;

  /// Consent screen, second of three points: its bold lead, followed by consentRetentionBody. Part of the versioned wording of the explicit consent under Art. 9 (2) (a) GDPR: changing it means bumping consentVersion.
  ///
  /// In en, this message translates to:
  /// **'Never used for training, never kept.'**
  String get consentRetentionLead;

  /// Consent screen, second point, after its lead: what the model provider may not do with the text, and where entries are stored. Part of the versioned wording of the explicit consent under Art. 9 (2) (a) GDPR: changing it means bumping consentVersion. Must agree with the privacy notice at getemotely.com/app-privacy.
  ///
  /// In en, this message translates to:
  /// **'Every request routes only to providers contractually barred from training on what you write and from keeping it after they answer. Your entries themselves are stored in Frankfurt and nowhere else.'**
  String get consentRetentionBody;

  /// Consent screen, third of three points: its bold lead, followed by consentWithdrawalBody. Part of the versioned wording of the explicit consent under Art. 9 (2) (a) GDPR: changing it means bumping consentVersion.
  ///
  /// In en, this message translates to:
  /// **'Sensitive, and yours to take back.'**
  String get consentWithdrawalLead;

  /// Consent screen, third point, after its lead: why the data is special-category, and that consent can be withdrawn (Art. 7 (3) GDPR). 'More' is the name of the app's second bottom tab and must match it. Part of the versioned wording of the explicit consent under Art. 9 (2) (a) GDPR: changing it means bumping consentVersion.
  ///
  /// In en, this message translates to:
  /// **'A journal can say how you feel, how you sleep or how your health is, so we ask first. You can withdraw on the More tab at any time; what a provider has already answered cannot be recalled.'**
  String get consentWithdrawalBody;

  /// Consent screen: the label of the checkbox, which is the affirmative act itself and always starts unticked. Part of the versioned wording of the explicit consent under Art. 9 (2) (a) GDPR: changing it means bumping consentVersion.
  ///
  /// In en, this message translates to:
  /// **'I consent to my journal entries being sent to a model provider as described above.'**
  String get consentCheckboxLabel;

  /// Consent screen button that records the consent; enabled only once the checkbox is ticked. Part of the versioned wording of the explicit consent under Art. 9 (2) (a) GDPR: changing it means bumping consentVersion.
  ///
  /// In en, this message translates to:
  /// **'Start journaling'**
  String get consentAgreeButton;

  /// Consent screen button that declines and goes back to the journal, which stays usable. Named plainly, because the choice has to be real. Also leaves the screen after a consent could not be recorded. Part of the versioned wording of the explicit consent under Art. 9 (2) (a) GDPR: changing it means bumping consentVersion.
  ///
  /// In en, this message translates to:
  /// **'Not now'**
  String get consentDeclineButton;

  /// Consent screen: read out by a screen reader on the disabled agree button, so someone who cannot see the checkbox knows why the button does nothing. An instruction for operating the screen, not a term agreed to: not part of the versioned wording.
  ///
  /// In en, this message translates to:
  /// **'Tick the box above to continue'**
  String get consentAgreeBlockedHint;

  /// Snack bar on the journal after the user declined consent: there is no session without the model, but everything else stays usable.
  ///
  /// In en, this message translates to:
  /// **'No problem. Nothing has been sent. You can still read the entries you already have, and you can start a session whenever you decide to.'**
  String get consentDeclinedMessage;

  /// Consent screen link that opens the full privacy notice in the browser (the notice itself is in English).
  ///
  /// In en, this message translates to:
  /// **'Read the full privacy notice'**
  String get consentReadNoticeLink;

  /// Consent screen, and a snack bar on the journal: the consent could not be recorded on the server, so no session starts.
  ///
  /// In en, this message translates to:
  /// **'Could not record your consent. Check your connection and try again.'**
  String get consentFailureMessage;

  /// Privacy settings, under the journal sessions switch: withdrawing consent could not be recorded, so consent still stands.
  ///
  /// In en, this message translates to:
  /// **'Could not withdraw your consent. Check your connection and try again.'**
  String get consentWithdrawFailureMessage;

  /// Consent screen and Privacy settings: the app could not find out whether consent already stands. Not the same as 'you have not consented'.
  ///
  /// In en, this message translates to:
  /// **'Could not check whether you have already agreed to this. Nothing has been sent. Check your connection and try again.'**
  String get consentUnknownMessage;

  /// Consent screen button, after reading or recording the consent failed: tries the same thing again.
  ///
  /// In en, this message translates to:
  /// **'Try again'**
  String get consentRetryButton;

  /// Consent screen button after whether consent stands could not be read: leaves the screen without answering, since nothing was asked.
  ///
  /// In en, this message translates to:
  /// **'Back'**
  String get consentBackButton;

  /// First-launch sheet heading: the usage-analytics question (PostHog, consent under § 25 TDDDG and Art. 6 (1) (a) GDPR). The companion speaks as 'I'. Part of the versioned usage-analytics wording: changing it means bumping usageAnalyticsVersion.
  ///
  /// In en, this message translates to:
  /// **'May I count how you use the app?'**
  String get usageAnalyticsTitle;

  /// First-launch sheet, under the question: why, in one breath. Part of the versioned usage-analytics wording: changing it means bumping usageAnalyticsVersion.
  ///
  /// In en, this message translates to:
  /// **'It shows which screens help and where people get stuck, so I can get better. What you write never goes into it.'**
  String get usageAnalyticsBody;

  /// First-launch sheet, next to a check mark: what is counted and where it is kept. Must agree with the privacy notice at getemotely.com/app-privacy. Part of the versioned usage-analytics wording: changing it means bumping usageAnalyticsVersion.
  ///
  /// In en, this message translates to:
  /// **'Taps, screens and crash reports, stored with PostHog in the EU'**
  String get usageAnalyticsCounted;

  /// First-launch sheet, next to a cross: what is never counted. Part of the versioned usage-analytics wording: changing it means bumping usageAnalyticsVersion.
  ///
  /// In en, this message translates to:
  /// **'Never your answers, entries or name'**
  String get usageAnalyticsNever;

  /// First-launch sheet button that refuses usage analytics. Exactly as prominent as the allow button: a refusal has to be as easy as the yes. Part of the versioned usage-analytics wording: changing it means bumping usageAnalyticsVersion.
  ///
  /// In en, this message translates to:
  /// **'Don’t allow'**
  String get usageAnalyticsDenyButton;

  /// First-launch sheet button that allows usage analytics. Part of the versioned usage-analytics wording: changing it means bumping usageAnalyticsVersion.
  ///
  /// In en, this message translates to:
  /// **'Allow'**
  String get usageAnalyticsAllowButton;

  /// First-launch sheet, under the buttons: where the choice can be changed later. 'More' is the app's second bottom tab and 'Privacy settings' a row on it; both must match those screens. Part of the versioned usage-analytics wording: changing it means bumping usageAnalyticsVersion.
  ///
  /// In en, this message translates to:
  /// **'Change it any time under More › Privacy settings.'**
  String get usageAnalyticsChangeHint;

  /// First-launch sheet link that opens the privacy notice in the browser (the notice itself is in English). Not part of the versioned wording.
  ///
  /// In en, this message translates to:
  /// **'Privacy notice'**
  String get usageAnalyticsNoticeLink;

  /// App bar title of the More tab, which holds the profile, privacy, feedback and account settings. Same word as the app's bottom tab.
  ///
  /// In en, this message translates to:
  /// **'More'**
  String get moreTitle;

  /// More tab: heading of the section with Privacy settings and the privacy notice.
  ///
  /// In en, this message translates to:
  /// **'Privacy'**
  String get morePrivacySection;

  /// More tab: heading of the section with feedback and the imprint.
  ///
  /// In en, this message translates to:
  /// **'About'**
  String get moreAboutSection;

  /// More tab: heading of the last section, which holds only the row that deletes the account.
  ///
  /// In en, this message translates to:
  /// **'Account'**
  String get moreAccountSection;

  /// More tab row that opens the Privacy settings screen.
  ///
  /// In en, this message translates to:
  /// **'Privacy settings'**
  String get morePrivacySettingsRow;

  /// More tab, under the Privacy settings row: the journal-sessions consent stands. Shown next to the usage-analytics status, separated by a middle dot.
  ///
  /// In en, this message translates to:
  /// **'Journal: allowed'**
  String get moreJournalAllowedStatus;

  /// More tab, under the Privacy settings row: the journal-sessions consent does not stand, so no session can start.
  ///
  /// In en, this message translates to:
  /// **'Journal: off'**
  String get moreJournalOffStatus;

  /// More tab, under the Privacy settings row: usage analytics are allowed.
  ///
  /// In en, this message translates to:
  /// **'Usage analytics: on'**
  String get moreUsageAnalyticsOnStatus;

  /// More tab, under the Privacy settings row: usage analytics are refused or not answered.
  ///
  /// In en, this message translates to:
  /// **'Usage analytics: off'**
  String get moreUsageAnalyticsOffStatus;

  /// More tab row that opens the privacy notice in the browser (the notice itself is in English).
  ///
  /// In en, this message translates to:
  /// **'Privacy notice'**
  String get morePrivacyNoticeRow;

  /// More tab row that opens the mail app on a feedback mail to the team.
  ///
  /// In en, this message translates to:
  /// **'Send feedback'**
  String get moreFeedbackRow;

  /// More tab, under the feedback row: what the prefilled mail already contains, so nobody wonders whether it sends anything they wrote.
  ///
  /// In en, this message translates to:
  /// **'Opens your mail app. Carries your app version and device, nothing from your journal.'**
  String get moreFeedbackExplanation;

  /// More tab row that opens the legal imprint (§ 5 DDG) in the browser.
  ///
  /// In en, this message translates to:
  /// **'Imprint'**
  String get moreImprintRow;

  /// More tab row, in the error colour, that opens the account deletion screen.
  ///
  /// In en, this message translates to:
  /// **'Delete account'**
  String get moreDeleteAccountRow;

  /// More tab, under the delete account row: what deleting means.
  ///
  /// In en, this message translates to:
  /// **'Removes your account and every entry.'**
  String get moreDeleteAccountExplanation;

  /// More tab, the profile card at the top: shown instead of the name while it is being read or could not be read.
  ///
  /// In en, this message translates to:
  /// **'Your profile'**
  String get profileCardTitle;

  /// More tab, the profile card at the top: an invitation shown instead of the name while the user has none.
  ///
  /// In en, this message translates to:
  /// **'Add your name'**
  String get profileCardAddName;

  /// App bar title of the Privacy settings screen, which holds a switch for each of the two consents.
  ///
  /// In en, this message translates to:
  /// **'Privacy settings'**
  String get privacySettingsTitle;

  /// Privacy settings: title of the switch for the explicit consent a journaling session needs.
  ///
  /// In en, this message translates to:
  /// **'Journal sessions'**
  String get privacyJournalLabel;

  /// Privacy settings, under the journal sessions switch: what the consent covers. Not the consent wording itself, which is on the consent screen.
  ///
  /// In en, this message translates to:
  /// **'Your answers go to a language model to guide each session. Never used for training, never kept by the provider.'**
  String get privacyJournalExplanation;

  /// Privacy settings, small print under the journal sessions switch while it is on.
  ///
  /// In en, this message translates to:
  /// **'Turning this off stops new sessions; your entries stay.'**
  String get privacyJournalOnNote;

  /// Privacy settings, small print under the journal sessions switch while it is off.
  ///
  /// In en, this message translates to:
  /// **'Off: no new session can start. Turning it on shows you what you agree to first.'**
  String get privacyJournalOffNote;

  /// Privacy settings, small print under the journal sessions switch, before privacyJournalOnNote: the day the standing consent was given.
  ///
  /// In en, this message translates to:
  /// **'Given {date}.'**
  String privacyJournalGiven(DateTime date);

  /// Privacy settings button under the journal sessions switch after whether consent stands could not be read: reads it again.
  ///
  /// In en, this message translates to:
  /// **'Check again'**
  String get privacyJournalRetryButton;

  /// Privacy settings: title of the dialog that asks once before withdrawing the journal-sessions consent.
  ///
  /// In en, this message translates to:
  /// **'Turn off journal sessions?'**
  String get privacyConfirmTitle;

  /// Privacy settings: body of the dialog that asks once before withdrawing the journal-sessions consent.
  ///
  /// In en, this message translates to:
  /// **'New sessions stop; your entries stay.'**
  String get privacyConfirmMessage;

  /// Privacy settings dialog button that withdraws the journal-sessions consent.
  ///
  /// In en, this message translates to:
  /// **'Turn off'**
  String get privacyConfirmButton;

  /// Privacy settings dialog button that keeps the journal-sessions consent as it is.
  ///
  /// In en, this message translates to:
  /// **'Cancel'**
  String get privacyCancelButton;

  /// Privacy settings: title of the switch for usage analytics (PostHog).
  ///
  /// In en, this message translates to:
  /// **'Usage analytics'**
  String get privacyUsageAnalyticsLabel;

  /// Privacy settings, under the usage analytics switch: what is counted and why. The companion speaks as 'I'.
  ///
  /// In en, this message translates to:
  /// **'Taps, screens and crash reports, so I can see what helps and where people get stuck. Never what you write.'**
  String get privacyUsageAnalyticsExplanation;

  /// Privacy settings, small print under the usage analytics switch: where the data is kept.
  ///
  /// In en, this message translates to:
  /// **'Stored with PostHog in the EU.'**
  String get privacyUsageAnalyticsNote;

  /// Privacy settings link that opens the privacy notice in the browser (the notice itself is in English).
  ///
  /// In en, this message translates to:
  /// **'Read the privacy notice'**
  String get privacyNoticeLink;

  /// App bar title of the Profile screen: the user's name, the account they sign in with, and signing out.
  ///
  /// In en, this message translates to:
  /// **'Profile'**
  String get profileTitle;

  /// Profile screen: label of the text field holding the name emotely greets the user by.
  ///
  /// In en, this message translates to:
  /// **'Name'**
  String get profileNameLabel;

  /// Profile screen: hint in the empty name field, in the companion's voice.
  ///
  /// In en, this message translates to:
  /// **'What should I call you?'**
  String get profileNameHint;

  /// Profile screen, under the name field while the name is one the user gave: what the name is for.
  ///
  /// In en, this message translates to:
  /// **'How emotely greets you.'**
  String get profileNameHelper;

  /// Profile screen, under the name field while the name is a placeholder name emotely picked when the user skipped giving one: an invitation in the companion's voice, never a demand.
  ///
  /// In en, this message translates to:
  /// **'{name} · a name I picked – tell me yours'**
  String profilePlaceholderLine(String name);

  /// Profile screen snack bar: the new name is saved.
  ///
  /// In en, this message translates to:
  /// **'Saved'**
  String get profileSavedMessage;

  /// Profile screen snack bar: the name field was emptied, so the saved name is shown again.
  ///
  /// In en, this message translates to:
  /// **'A name needs at least one character.'**
  String get profileNameEmptyMessage;

  /// Profile screen snack bar: the name holds a character that cannot be stored (a tab, a line break), so the saved name is shown again.
  ///
  /// In en, this message translates to:
  /// **'That name has a character I can’t use.'**
  String get profileNameRefusedMessage;

  /// Profile screen snack bar: the server did not take the name, so the saved one is shown again.
  ///
  /// In en, this message translates to:
  /// **'I couldn’t save that name. Try again in a moment.'**
  String get profileSaveFailedMessage;

  /// Profile screen, in place of the name field: the name could not be read.
  ///
  /// In en, this message translates to:
  /// **'I couldn’t load your name.'**
  String get profileLoadFailedMessage;

  /// Profile screen button after the name could not be read: reads it again.
  ///
  /// In en, this message translates to:
  /// **'Try again'**
  String get profileRetryButton;

  /// Profile screen: heading above the read-only address the account signs in with.
  ///
  /// In en, this message translates to:
  /// **'Signed in as'**
  String get profileSignedInAsLabel;

  /// Profile screen row at the foot that signs the user out.
  ///
  /// In en, this message translates to:
  /// **'Sign out'**
  String get profileSignOutButton;

  /// Profile screen and the More tab's profile card: shown instead of the address when the user chose Apple's Hide My Email, since the address is one Apple made up.
  ///
  /// In en, this message translates to:
  /// **'Hidden by Apple'**
  String get signInHiddenByApple;

  /// Profile screen, under the address: the account signs in with a code sent by email.
  ///
  /// In en, this message translates to:
  /// **'Via email code. This is where sign-in codes and account mail go.'**
  String get signInViaEmailCode;

  /// Profile screen, under the address: the account signs in with Google.
  ///
  /// In en, this message translates to:
  /// **'Via Google. This is where account mail goes.'**
  String get signInViaGoogle;

  /// Profile screen, under the address: the account signs in with Apple and shares its real address.
  ///
  /// In en, this message translates to:
  /// **'Via Apple. This is where account mail goes.'**
  String get signInViaApple;

  /// Profile screen, under the address: the account signs in with Apple and hides its address behind Apple's private email relay.
  ///
  /// In en, this message translates to:
  /// **'Hidden by Apple (private relay). Apple forwards account mail to you.'**
  String get signInViaAppleRelay;

  /// Profile screen, under the address: the account signs in some way the app does not offer (set up by hand).
  ///
  /// In en, this message translates to:
  /// **'This is where account mail goes.'**
  String get signInViaUnknown;

  /// App bar title of the account screen, whose one purpose is deleting the account.
  ///
  /// In en, this message translates to:
  /// **'Account'**
  String get accountTitle;

  /// Account screen: what deleting the account means, said once before the button.
  ///
  /// In en, this message translates to:
  /// **'Deleting your account also deletes every journal entry you wrote. There is no way back.'**
  String get accountConsequenceMessage;

  /// Account screen button, in the error colour, that asks for confirmation before deleting the account.
  ///
  /// In en, this message translates to:
  /// **'Delete account'**
  String get accountDeleteButton;

  /// Account screen: the confirmation dialog's question, naming the loss.
  ///
  /// In en, this message translates to:
  /// **'Delete your account and every entry?'**
  String get accountConfirmationMessage;

  /// Account screen confirmation dialog button that keeps the account.
  ///
  /// In en, this message translates to:
  /// **'Cancel'**
  String get accountCancelButton;

  /// Account screen confirmation dialog button, in the error colour, that deletes the account and every entry for good.
  ///
  /// In en, this message translates to:
  /// **'Delete'**
  String get accountConfirmDeleteButton;

  /// Account screen: deleting the account failed or the answer never arrived.
  ///
  /// In en, this message translates to:
  /// **'Could not delete your account. Check your connection and try again.'**
  String get accountFailureMessage;

  /// Account screen button after deleting failed: tries to delete the account again.
  ///
  /// In en, this message translates to:
  /// **'Try again'**
  String get accountRetryButton;

  /// Account screen button after deleting failed: signs out, since the account may already be gone on the server.
  ///
  /// In en, this message translates to:
  /// **'Sign out'**
  String get accountSignOutButton;
}

class _AccountLocalizationsDelegate
    extends LocalizationsDelegate<AccountLocalizations> {
  const _AccountLocalizationsDelegate();

  @override
  Future<AccountLocalizations> load(Locale locale) {
    return SynchronousFuture<AccountLocalizations>(
      lookupAccountLocalizations(locale),
    );
  }

  @override
  bool isSupported(Locale locale) =>
      <String>['de', 'en'].contains(locale.languageCode);

  @override
  bool shouldReload(_AccountLocalizationsDelegate old) => false;
}

AccountLocalizations lookupAccountLocalizations(Locale locale) {
  // Lookup logic when only language code is specified.
  switch (locale.languageCode) {
    case 'de':
      return AccountLocalizationsDe();
    case 'en':
      return AccountLocalizationsEn();
  }

  throw FlutterError(
    'AccountLocalizations.delegate failed to load unsupported locale "$locale". This is likely '
    'an issue with the localizations generation tool. Please file an issue '
    'on GitHub with a reproducible sample app and the gen-l10n configuration '
    'that was used.',
  );
}
